### ISSUE TITLE
Adorned crosstab doesn't pass percentages to arrange as expected

### ISSUE THREAD

**Issue by dsdesrosiers** [sfirke/janitor#119]
df %>% crosstab (val1, val2) %>% adorn_crosstab() %>% arrange (desc(top))

where "top" is one of the values of Val2

the output is sorted by percent except that all the 100%s are after everybody else except the 0%-ers. In other words, the output starts at top = 99%...decreases to 1% then shows my 100% achievers, then my 0% achievers. Happy to anonymize some data to share if this doesn't make sense.

**Comment by sfirke** [comment]
Thanks for reporting this.  I think I follow; once the %s are appended, the columns are of class character, and so they sort alphabetically - in which case the numbers 70%, 6%, 40%, 100%, 0% are all in alphabetically-descending order.

```
library(janitor)
library(dplyr)
mtcars %>% crosstab(carb, am) %>% adorn_crosstab() %>% arrange(desc(`1`))
#>   carb          0          1
#> 1    1  42.9% (3)  57.1% (4)
#> 2    2  60.0% (6)  40.0% (4)
#> 3    4  70.0% (7)  30.0% (3)
#> 4    6   0.0% (0) 100.0% (1)
#> 5    8   0.0% (0) 100.0% (1)
#> 6    3 100.0% (3)   0.0% (0)
mtcars %>% crosstab(carb, am) %>% adorn_crosstab("col") %>% arrange(desc(`1`))
#>   carb         0         1
#> 1    6  0.0% (0)  7.7% (1)
#> 2    8  0.0% (0)  7.7% (1)
#> 3    1 15.8% (3) 30.8% (4)
#> 4    2 31.6% (6) 30.8% (4)
#> 5    4 36.8% (7) 23.1% (3)
#> 6    3 15.8% (3)  0.0% (0)
```
This is a limitation of the current approach, but I'm working on breaking out the `adorn_crosstab` function into pieces that operate separately (#101).  Under that paradigm, you'd calculate the percentages, _then_ do your `arrange` while the values are numeric, then round + append the `%` sign to make them characters.  I'll close this issue when I eventually merge that branch in.

**Comment by dsdesrosiers** [comment]
Your understanding is perfect. Thanks for the quick response. I'll be sure to stay up to date. 

FYI every data read line of code I write ends with %>% clean_names()!

**Comment by sfirke** [comment]
The new API allows for this quite nicely! 🎈 

```
mtcars %>%
  tabyl(carb, am) %>%
  arrange(desc(`1`)) %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting() %>%
  adorn_ns()
```

When pull request #138 gets merged, this will be live on the development version!

**Comment by sfirke** [comment]
hey @dsdesrosiers - check out the development version and the new tabyls vignette (linked from the main repo page), this functionality is now live

**Comment by dsdesrosiers** [comment]
@sfirke - this is wonderful, thank you. I haven't been in R as much as I'd like but tonight I made a point to really sit down with this fix and it seems to work perfectly. No doubt I'll be making use of the new functionality. Thank you for the continued efforts with this package.
