### ISSUE TITLE
suggestion add function that deals with excel currencies

### ISSUE THREAD

**Issue by marcoblume** [sfirke/janitor#129]
Hi,

thank you for the package. clean_names() has been really helpful.

Would it be possible to add a function that deals with the currencies formats that exist in excel and correctly transforms the strings into numeric values?

As far as I can see these are the most currencies format that excel offers

$100.12
-$222.22
($222.22) 
100.12 £
-222.22 £

Thanks in advance

**Comment by sfirke** [comment]
Hi Marco,

Thanks for the note and idea.  Have you tried `readr::parse_number()`?  It handles all of the above instances except that if you want the wrapping parentheses to indicate negative, you'd need to first replace a leading parenthesis with a negative sign using `gsub` or similar.

**Comment by marcoblume** [comment]
Hi,

thanks for the answer. I have been recommending your package  to colleagues of mine who are not that familiar with R, who often read in Excel data. Your package has been a blessing for them as it helps them get started right away thanks to clean_names(). 
``gsub``` is a little too daunting for them at this stage and as you said ``` parse_number()``` does almost the entire job just falls short on the (222$) numbers but I'll write a function for them that will do that for them.

**Comment by sfirke** [comment]
Sounds good.  Here's a lead for your function to handle the numbers in parentheses: https://stackoverflow.com/questions/5068705/processing-negative-number-in-accounting-format looks like lots of other folks have run into this so maybe you can adapt from another user's code or package.
