### ISSUE TITLE
export to latex?

### ISSUE THREAD

**Issue by randomgambit** [sfirke/janitor#133]
Hi @sfirke,

I think it would be very useful if one could export the tables generated by `janitor `in `tex` format. What do you think?

Thanks!

**Comment by sfirke** [comment]
Hrm.  I have never worked in LaTeX myself, so don't know what this would entail or how to implement it.  The janitor tables are data.frames; are there other packages that export them to tex?

**Comment by sfirke** [comment]
This falls under the category of "if someone has a vision and wants to implement it, comment and we'll reopen it" - but it's not something I grasp or could implement.
