### ISSUE TITLE
Should the leading # symbol in a variable name get eliminated by clean_names()?

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#142]
Now is the time to mess with `clean_names` once and for all, as long as it's breaking.  Don't want to re-break it and offer a 2nd legacy option...

`Avg # days` gets turned into `avg_days` = good.
`# Students Tested 15-16` turns into `x_students_tested_15_16` - not good.  I think I'd prefer just `students_tested_15_16`.

Note: This may be broader than the # character and have to do with leading vs. not.  Need to play around with it and see.

**Comment by rgknight** [comment]
What if you just replaced # with "num"? Then it would make sense no matter
where placed. Evaluating differently based on order adds complexity.

**Comment by sfirke** [comment]
I was unclear - don't mean to evaluate based on order, I'm just remarking on two things: the treatment of the `#` character specifically and the fact that string-initial special characters get turned into `x_` while they disappear in the middle of the string.

But I agree with your suggestion.  Should `#` become "num" or "number"?  "number" is more consistent with `%` -> `"percent"` and not `"perc"`.

Then I'm thinking I'll also eliminate string-initial punctuation characters, so `! a weird string` becomes `a_weird_string` and not `x_a_weird_string".

**Comment by sfirke** [comment]
Added the above (my most recent comment) to the dev version
