### ISSUE TITLE
tabyl no longer accept more than one variable

### ISSUE THREAD

**Issue by nunnally** [sfirke/janitor#147]
Hi,

I tried to follow your examples, howerver, the tabyl function no longer accept more than one columns from the data.frame.

**Comment by sfirke** [comment]
Hrm, sorry to hear that.  So that I can debug, can you share a reprex (reproducible example)?  Ideally the code you're running and the data you're running it on.

**Comment by sfirke** [comment]
Hi @nunnally, I'll close this issue for now as I tidy up.  If you're able to reproduce the problem, please feel free to re-open the issue, posting your example.
