### ISSUE TITLE
95% confidence intervals

### ISSUE THREAD

**Issue by mbcann01** [sfirke/janitor#148]
Hi Sam,

When working with categorical data, I often need/want to estimate 95% confidence intervals. I was surprised how hard this is to do "out of the box" in R - especially in a dplyr pipeline (unless I'm just missing something). 

So, I made my own little function for this purpose. I'm sure there's a lot of room for improvement, but it seems to get the job done. When I came across your tabyl function, I thought it might be something you were interested in incorporating. If not, no big deal.

In case you are interested, here is a link to my code: https://github.com/brad-cannell/bfuncs/blob/master/R/freq_table.R

Brad

**Comment by sfirke** [comment]
Thanks for sharing this!  The function looks great and I agree it's similar to `tabyl`.

I dig this function.  But it feels a little out of scope for janitor; there'd be overlap with `tabyl` and it is farther along the spectrum toward data analysis vs. data cleaning.  I'm already pushing it w/r/t janitor having a coherent mission vs. being a utilities package 🙃  

It seems like a good starting point for a tidyverse-aligned package of data analysis functions that folks like social scientists would miss coming from SAS and Stata where there may be a more baked-in function (to your point about out-of-the-box difficulty in R).  I'm not sure if such a package exists, I'd say it's a hole in the tidyverse and beginner-friendly R universe... in the meantime I'll refer folks to this function for calculating 95% CIs 👍

**Comment by mbcann01** [comment]
Makes total sense. Thanks for your consideration!
