### ISSUE TITLE
[Feature Request] Add '...' argument to clean_names() for selection of columns

### ISSUE THREAD

**Issue by everetr** [sfirke/janitor#152]
dplyr::select() contains a '...' argument allowing for a subset of an input tibble's columns to be selected. I suggest that janitor::clean_names() should contain a '...' argument allowing the user to specify a subset of an input tibble's columns whose names will be cleaned. All unspecified columns will have their names untouched. (clean_names() will return all columns, not just a subset.)

In the wild, sometimes one has a dataset with certain columns whose names are untouchable, because management says so or otherwise. In its current state, clean_names() bluntly cleans all names of the input tibble. 

```r
library(tidyverse)
library(janitor)

# '123.Important.ID' is some variable whose name I don't want to clean, for whatever reason.
df = tribble(
  ~Var1, ~Var2, ~Var3, ~`123.Important.ID`,
  1, 10, 0.1, '0001',
  3, 30, 0.22, '0002',
  15, 150, 0.33, '0003')

# Desired input and output.
clean_names(dat = df, Var1:Var3)
#> [1] "var1"             "var2"             "var3"            
#> [4] "123.Important.ID"

```

**Comment by sfirke** [comment]
Thanks for suggesting this.  I've thought about it a bit and am open to it.  There's not much cost; it doesn't affect how `clean_names` works now and only makes the function's interface a little more complex.  I also don't see this as a critically-important feature, but see how it might be handy.

I expect it could be implemented using the helper functions as `dplyr::select`, e.g., `one_of()` or in your example `-`123.Important.ID`.

@rgknight and @chrishaid what do you two think re: whether this should be implemented?

**Comment by rgknight** [comment]
I think this is a great idea and should be implemented. 

Another option would be to make `case_when_at` that would allow folks to do this, following the `mutate_at` formula.

@everetr would you be interested in taking a stab at building this out?

**Comment by everetr** [comment]
I can give it a shot, since it's not critically important.

**Comment by sfirke** [comment]
@everetr I didn't mean to demean your suggestion by saying it's not critically-important.  I'm just aware of my own slow velocity and thus wanted to hear from others before green-lighting it (given that I'm moving slowly in dragging this across the line to CRAN for a v1.0 release).  If you can take a shot at this, let's try to squeeze it in!

Note that the dev version of janitor (master branch of this repo) now has `case` as the 2nd argument to clean names.  So the example you give would have to be tweaked for this, and users specifying column names to `...` would need to specify a `case` as well.  Just wanted to make sure you're building from the latest version.

If you can include tests in your pull request, that would be excellent.  And if you'd like to discuss your approach, or protocol for contributing, please do.

**Comment by sfirke** [comment]
Also, you're at EdBuild?  Very cool, I loved Fault Lines.  Hooray for this issue being full of people from the K-12 ed space 🍎

**Comment by sfirke** [comment]
I haven't played with this idea, but what comes to mind is dplyr::select the data.frame with the `...` argument.  Preserve the original names in a variable.  Then clean all names as is the case currently, but put back the original names in columns that match the names of the data.frame selected with `...`.

There may be better ways, this is just what jumped to mind for me.

**Comment by everetr** [comment]
@sfirke No worries! I didn't take it like that. I just understood you have other things going on and wanted to signal that it may be slow going for me.

I'm glad you liked Fault Lines! I'll pass that along. Stay tuned for more stuff along those lines ;)

I'll take a look and come back with my thoughts soon. Thanks for the help!

**Comment by jestarr** [comment]
@sfirke First off, awesome package!  I was going to ask about this as well.  Is there a solution to this use case?  I'm running into the same exact issue.

**Comment by sfirke** [comment]
Thanks for bumping this @jestarr.  I think this should be a priority and should not be too hard to implement.  Anyone is welcome to submit a pull request implementing the tidyverse-style `...` column selection.  Also add'l questions and discussion welcome.

**Comment by sfirke** [comment]
`clean_names` now uses the `...` argument to pass add'l arguments to `snakecase::to_any_case` and I feel good about that.  Which probably takes this suggestion off the table unless others have different implementation ideas.

I acknowledge this is a not-uncommon real world problem so if people are working around it in the current `clean_names`, please do post your approach.  The existence of `make_clean_names` makes this a little easier.  Here's my approach, doesn't have the power of tidyselect helpers unfortunately:

```
x <- iris
names(x)[!stringr::str_detect(names(x), "Length")] <-
  janitor::make_clean_names(
    names(x)[!stringr::str_detect(names(x), "Length")]
  )
names(x)

[1] "Sepal.Length" "sepal_width"  "Petal.Length" "petal_width"  "species"
```
