### ISSUE TITLE
pkgdown site for janitor?

### ISSUE THREAD

**Issue by pgensler** [sfirke/janitor#156]
It would be really helpful to have a pkgdown site for janitor, as I find myself often guiding people to the github page, which can be a bit intimidating for newcomers to the package. Thanks.

**Comment by sfirke** [comment]
This is a great idea!  Putting it on the list for 2018.  Thanks.

**Comment by sfirke** [comment]
Got the basics up and running: https://sfirke.github.io/janitor/.  Need to customize.

**Comment by pgensler** [comment]
That is amazing, do you mind if I tweet it? I think quite a few people would find it useful.

**Comment by sfirke** [comment]
That would be lovely!  Though I wish it was done-r before making it public, e.g., there are headers not appearing correctly on the main page.  How 'bout give me a few days in case I get to it and then at that point, I won't let perfect be the enemy of good ⚖️ and will just appreciate your publicity offer either way 😃

**Comment by sfirke** [comment]
hey @pgensler the pkgdown site is good enough now if you're still up for promoting it!  Might tweak it more someday but I'm calling it done for launching janitor v.1.0 which is now on GitHub.

**Comment by pgensler** [comment]
Do you have a link to it? I'm not seeing one in the readme, but maybe I'm missing it.

**Comment by almartin82** [comment]
https://sfirke.github.io/janitor/
