### ISSUE TITLE
print clean_names() dput output as a side effect

### ISSUE THREAD

**Issue by Tazinho** [sfirke/janitor#158]
More of a suggestion than an issue:
Since clean_names() is very highlevel, it might be nice to let it print
`print(dput(new_names))` as a side effect to the console, before returning.

In this way a user might directily visually inspect if `clean_names()` succeded and also introduce small corrections hardcoded afterwards more quickly, when `clean_names()` didn't work as expected, for example because of bad input...

Some import functions (for example from the **readr**) package use a similar idea to notify the user, which type guesses have been made for the columns.

**Comment by sfirke** [comment]
Thanks for this idea!  I hear you on the comparison to readr's output.  I find the readr output handy the first time, then unnecessary red print in the console the 100th time I run the script.

I expect with `clean_names()` the printing of (possibly dozens or hundreds of) names to the console might get tiresome, so will leave as is for now and close this as I tidy up issues.
