### ISSUE TITLE
[Feature Request] allow removing repetitions with clean_names()

### ISSUE THREAD

**Issue by ikashnitsky** [sfirke/janitor#160]
Quite often unclean headers contain unnecessary repetitive parts (see the example below). It would be nice to have an argument within `clean_names()` to get rid of some patterns. 

```
library(tidyverse)
library(magrittr)
library(janitor)


# Altmetric top 100 papers in 2017
df <- read_csv("https://ndownloader.figshare.com/files/9948691") %>% 
        remove_empty_rows() %>% 
        clean_names()

# The way I remove the repetitions now
names(df) %<>% str_replace("number_of_", "") 
```

**Comment by sfirke** [comment]
Hi Ilya,

Thanks for this idea.  Weighing the gain (small time savings for a small number of users) vs. the cost (adding an argument = a small decrease in documentation clarity but for a large number of users), I think this is too specific a use case to add to `clean_names()`.  Your current solution looks elegant and maximally-efficient to me!

Sam
