### ISSUE TITLE
See if get_dupes() can be refactored to use dplyr::add_count_

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#163]
I'd originally drawn up the function to use `dplyr::n()` but I couldn't call that function programmatically.  Thus I use an `inner_join` to the result of `count`, which is slow on large data sets.  I wonder if `add_count` which calls `add_tally` would speed up the code?  At the very least it would make it shorter.

Create a 2nd version of `get_dupes` and benchmark them to see.

**Comment by rgknight** [comment]
Could you also group the data then use the group size function as Hadley
suggested?

**Comment by sfirke** [comment]
Whoa.  I could use the group sizes stored in the attributes of a grouped data.frame.  Heck I could use that for one-way tabyls too.

I don't think I saw Hadley write about this, can you share a reference?  I wonder why `add_tally` itself calls `n()` instead of using these attributes, see line 70 of https://github.com/tidyverse/dplyr/blob/master/R/count-tally.R.

**Comment by rgknight** [comment]
Good Q re: add_tally, might be worth asking in the tidyverse forum thing. I
thought Hadley suggested that in reply to a Tweet by you like last week but
I may be misremembering.

**Comment by sfirke** [comment]
Ugh I created a version that uses `add_count_` to eliminate the need for a join ... and it's 50-70% _slower_ than the current `get_dupes()` function ⏳   New version at https://github.com/sfirke/janitor/commit/b6c3ced8565a0c19cb78a37a6c9ead1dcf7265e0.

**Comment by sfirke** [comment]
Ryan, I posted on the RStudio Community forum as you suggested: https://community.rstudio.com/t/why-does-combining-count-inner-join-outperform-add-count/4084  With a reprex showing `add_count` to be significantly slower than `count` + `inner_join`.

**Comment by sfirke** [comment]
Closed by https://github.com/sfirke/janitor/commit/41dc3f1f11f9755eb09454b6635b7257f35d1e5b - implements `add_count` instead of a join.
