### ISSUE TITLE
Coordinate CRAN versions with snakecase

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#182]
Right now `clean_names` depends on the dev version of snakecase from GitHub, for the correct parsing option 4.

Should I include code like this:
```
if (packageVersion("snakecase") < "0.8.3.1") {
  warning("the results of clean_names() may change slightly if
  you upgrade the snakecase package in the future.  Suggest upgrading
  now to snakecase >= 0.8.3.1 for consistent results.", call. = FALSE)
}
```

If the new snakecase is on CRAN by then, I could just specify dependency on that version.  Though [R Packages](http://r-pkgs.had.co.nz/release.html) suggests that this is not good, as it forces an upgrade of snakecase that could break other functionality for the user.  I'm not sure how often that'll be the case...

If the new snakecase is NOT on CRAN by the time janitor 1.0 ships, then I should definitely include this warning.  Try to avoid that though, as not everyone knows how to install from GitHub and that warning will get annoying.

**Comment by sfirke** [comment]
I think this could be:
```
if (packageVersion("snakecase") > "0.8.3") {
     parsing_option <- 4
    )
} else {
  parsing_option <- 6
}
```
EDIT: actually, I don't see any parsing option on the current CRAN version that matches the dev/GitHub version 4 so perhaps it's not as simple as this last idea here.  @Tazinho, what would you advise for approaching the issue that `clean_names` behavior depends on `snakecase` version?

**Comment by Tazinho** [comment]
No idea. However, I am going to update now :)

Von meinem iPhone gesendet

**Comment by Tazinho** [comment]
Can't you make it dependent on the next snakecase version, then users should get automatically get updated their snakecase version when installing janitor.

**Comment by Tazinho** [comment]
In dplyr it's done in the same way
https://github.com/tidyverse/dplyr/blob/master/DESCRIPTION

**Comment by sfirke** [comment]
Yes, I am fine with forcing an update to the newest version of snakecase,
as long as it's on cran already so that people can do that update.

**Comment by sfirke** [comment]
snakecase 0.9 is now on CRAN and required by janitor
