### ISSUE TITLE
Need help making logo smaller in filesize, saving as specific size .png (current in .ai format)

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#184]
It would be neat to add the hex sticker to this library: http://hexb.in/

The specs for adding to the library are here: https://github.com/maxogden/hexbin

Someone would need to get the .ai file down from 1.5 MB to 500kb, and save it as a png with specific dimensions.  I don't have Adobe Illustrator or know how to do this; if you can do this, it would be a nice way to contribute!  I can't add the file here because it's a .ai file not supported by GitHub, but reply or email me if you can help and I'll get it to you.

**Comment by martgnz** [comment]
Hey! 👋 I would love to help with this. I have Illustrator and use janitor a lot.

**Comment by sfirke** [comment]
Thank you! I will post the files somewhere (can't attach these files types
to Github) and then reply in more detail later.

On Mar 10, 2018 9:13 AM, "Martín González" <notifications@github.com> wrote:

Hey! 👋 I would love to help with this. I have Illustrator and use janitor
a lot.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sfirke/janitor/issues/184#issuecomment-372032975>, or mute
the thread

**Comment by martgnz** [comment]
Any updates? 👀

**Comment by billdenney** [comment]
I just opened it in Inkscape, removed a couple of what appeared to be unnecessary embedded .png files, and here it is as a .svg.
[janitor_sticker.zip](https://github.com/sfirke/janitor/files/4434566/janitor_sticker.zip)

**Comment by billdenney** [comment]
Here are both the .png with the right size and a slightly different .svg without the pink border.
[janitor_sticker.zip](https://github.com/sfirke/janitor/files/4437704/janitor_sticker.zip)

**Comment by billdenney** [comment]
@sfirke, nudge on this one-- I made the icon and attached it to the prior comment.  (Since I don't own the original .ai file, I wouldn't meet the guidelines for making the pull request.)

**Comment by sfirke** [comment]
Thanks @billdenney.  I submitted the PR here: https://github.com/maxogden/hexbin/pull/283  Only noticed at the end of the process that it looks like there's quite the backlog of PRs since April; oh well, hope it gets merged eventually.  I'll close this here.
