### ISSUE TITLE
Should remove_empty have a default argument for which

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#188]
@garthtarr writes in #187:

> In `remove_empty()`, `which` should be set. I'd encourage a which = c("rows","cols") as the default (maybe it's just me, but I almost always use remove_empty_rows() and remove_empty_cols() together).

My thinking was:
* it's more readable code to force the user to write `remove_empty("rows")` vs. just `remove_empty()` where it's unclear to someone unfamiliar with janitor what's being removed.
* it forces what I feel is the more cautious, intentional behavior of checking first to see if there are empty rows and empty columns, and that they should be removed (vs. say, prompting a fix upstream to the data source).

I think this relates to #70.  If there were messages by default for what was removed by `remove_empty`, then I'd be less wary of having a default argument of `c("rows", "cols")`.

**Comment by garthtarr** [comment]
I take your points about readability and caution.  I do feel that not having any default set is a bit odd... I could be wrong, but it feels like most functions in R work with some sensible defaults when the data is passed to them.  Imagine if the `na.rm` argument to the `mean()` function didn't have a default, so you every time you use it (I often still have to manually set it to `na.rm = TRUE` but at least it works when only specifying the data).

```r
# every time!!
mean(x, na.rm = FALSE)
mean(x, na.rm = TRUE)
```

I think the verbose option #70 (defaulting to yes) would be really helpful when combined with a default of `which = c("rows", "cols")` or even if it's just `which = "rows"` as the default.

**Comment by sfirke** [comment]
I am working on this right now and have been convinced that this should work with no default argument.  What do you think about: it defaults to `c("rows", "cols")` if nothing is specified, but prints a message saying it's doing that?  Users annoyed by that message can suppress it by actually writing out `c("rows", "cols")`.

**Comment by sfirke** [comment]
@garthtarr I added this functionality and remain interested in your opinion as the advocate for it :mega:

**Comment by garthtarr** [comment]
I think this is a very good solution.  I just tried it out and it works well.  The one slightly odd thing is that it will still print the warning even if dat is not supplied and the function fails.  Not at all urgent, but perhaps there should be a check that the `dat` argument is supplied first?

```s
> janitor::remove_empty()
value for "which" not specified, defaulting to c("rows", "cols")
Error in janitor::remove_empty() : 
  argument "dat" is missing, with no default
```

**Comment by sfirke** [comment]
Just implemented that, thanks.
