### ISSUE TITLE
Tabyl Sorting

### ISSUE THREAD

**Issue by scottfrechette** [sfirke/janitor#192]
Whenever I call tabyl I include sort = TRUE but with the newest update it's no longer sorting. 

```r
tabyl(mtcars, cyl, sort = TRUE)
```

**Comment by sfirke** [comment]
Yep, the 1.0.0 update broke that.  You may want to see the full release notes here: http://sfirke.github.io/janitor/news/index.html

There you'll see the excerpt: 
> Existing code that relies on the version of tabyl present in janitor versions <= 0.3.1 will break if the sort argument was used, as that argument no longer exists in tabyl (use `dplyr::arrange()` instead).

**Comment by scottfrechette** [comment]
Read the notes and apparently glazed right over that part, my fault. Thanks for getting back to me so quickly.

**Comment by rachaelmburke** [comment]
Hi... sorry to bring this to here.  But I am completely confused as to how to now get a frequency table sorted in order of frequency?  "Sort" doesn't work anymore.  And I can't work out how to get "arrange" to work.

No matter what I do, or how the column in the df is ordered before I pass it to tabyl, or whether I use ordered factors or just characters.... the tabyl is always in alphabetical order.

Apologies if this is more more of a "help" request, than a bug... but I'm going mad here!

Rachael
