### ISSUE TITLE
Problems with ```tabyl``` to extract frequency tables of several factor variables with ```llply```

### ISSUE THREAD

**Issue by mvazquezs** [sfirke/janitor#198]
## Feature requests

I try to obtain with ```tabyl``` function frequency tables in a ```factor```variables. When you prove with only one variable the function works easy and fine, as example shown with a data.frame (```df```) and ```var_1```.

```r
df

  SEXc  avail var_1   var_2
   <fct> <int> <fct> <fct>
 1 M         1 NA    NA   
 2 F         1 NA    NA   
 3 M         0 3     1    
 4 F         0 1     0    
 5 M         0 3     3    
 6 F         0 1     NA   
 7 F         1 NA    NA   
 8 M         1 NA    NA   
 9 M         0 3     3    
10 F         0 1     3
```
```r
tab_1 <- df %>% filter(avail == 0) %>%
  tabyl(d_alc, SEXc, show_missing_levels = T) %>%
  adorn_totals(c('row', 'col')) %>%
  adorn_percentages('row') %>%
  adorn_pct_formatting(digits = 2) %>%
  adorn_ns() %>%
  adorn_title('combined')
```

```
 d_alc/SEXc           M           F       Total
          1 100.00% (1)   0.00% (0) 100.00% (1)
          0   0.00% (0) 100.00% (1) 100.00% (1)
          2       - (0)       - (0) 100.00% (0)
          3  66.67% (2)  33.33% (1) 100.00% (3)
       <NA>   0.00% (0) 100.00% (1) 100.00% (1)
      Total  50.00% (3)  50.00% (3) 100.00% (6)
```

---
## Bug report
However, when we define a vector  and introduce a loop to do ```n``` times  with ```llply``` function the code doesn't work. The function, called ```crosstab``` require of a data.frame and a vector of variables and use ```llply``` to do several tables in a list. It would be great to use ```tabyl``` in a loop to extract frequency tables in a list, as previous ```crosstab``` function. 
```r
## as.data.frame
df

## vector
var_fac <- c('var_1', 'var_2')
```

```r
## function code
crosstab <- function(phen, vars, stat = c('tidyverse', 'janitor'))
{
# arg
	stat <- match.arg(stat, c('tidyverse', 'janitor'))

# loop
	llply(vars, function(x) {
		phen$x <- phen[, x]


	# function
	tab_1 <- phen %>% filter(avail == 0) %>%
					 tabyl(x, SEXc, show_missing_levels = T) %>%
 					 adorn_totals('all') %>%
					 adorn_percentages('row') %>%
					 adorn_pct_formatting(digits = 2) %>%
					 adorn_ns() %>%
					 adorn_title('combined')
	# print	
	print(tab_1)
	})
}
```

The error appear when you tape the function with the arguments required:

```r
crosstab(df, var_fac)

Error in grouped_df_impl(data, unname(vars), drop) : 
  Column `x` can't be used as a grouping variable because it's a tbl_df/tbl/data.frame
```

Any solution available?

Thanks in advance

**Comment by sfirke** [comment]
Sorry I never responded to this.  tabyl has evolved a lot since this was originally posted, and `plyr::llply` has been replaced by the `map` functions in the purrr package.  So I'll close this issue -- but if it remains a pain point for you with `tabyl` and `map`, please open a new issue.
