### ISSUE TITLE
argument to clean_names() for maximum length of names?

### ISSUE THREAD

**Issue by jrosen48** [sfirke/janitor#201]
I recently read an Excel sheet with obscenely long variable names (i.e., twenty words in length). What do you think of an argument that would shorten (or even somehow summarize) very long variable names, maybe to a max. length of, say, 10-12 characters or 2-3 words? Just an idea.

**Comment by Tazinho** [comment]
Hi @jrosen48 I am currently writing a proposal for changes regarding `clean_names()`. Would some kind of `transliterations` argument have helped to solve your issue? E.g. sth like:

```r
to_any_case("very_supersupersupersuper_long_name",
             transliterations = c(`supersupersupersuper` = "super"))
[1] "very_super_long_name"
# or
to_any_case("un_china_france_greatbritain_russia_america",
             transliterations = c(`china` = "chi", 
                                  `france` = "fr", 
                                  `greatbritain` = "gb", 
                                  `russia` = "ru",
                                  `america` = "usa"))
[1] "un_chi_fr_gb_ru_usa"
```

Or do you have another option in mind?

**Comment by sfirke** [comment]
good idea thank you!  My response time is even longer than your variable names :weary: This is now being discussed on #332 so I'll close it here
