### ISSUE TITLE
janitor::tabyl & knitr::kable

### ISSUE THREAD

**Issue by capitanman** [sfirke/janitor#212]
## Feature requests
Hi, I like to use tabyl with knitr::kable in order to generate a nice human readable format.
In the 3 way table though the third variable is not displayed and the n tables appear indistinguishable between each other.
Is there a way to fix this?
Thanks

Brief description of the problem

```r
data("iris")
library(tidyverse)
library(janitor)
library(knitr)

# 3 way example
iris %>% 
   mutate(SepalLong = if_else(Sepal.Length > median(Sepal.Length), "SLong", "SShort"),
          PetalLong = if_else(Petal.Length > median(Petal.Length), "PLong", "PShort")) %>%
   tabyl(SepalLong, PetalLong, Species) %>%
   kable()
# in the 2 way and single table the kable output is perfect
```

**Comment by fernandovmacedo** [comment]
As a workaround, you can change your code like this:
```
```{r, results='asis'}
iris %>% 
  mutate(SepalLong = if_else(Sepal.Length > median(Sepal.Length), "SLong", "SShort"),
         PetalLong = if_else(Petal.Length > median(Petal.Length), "PLong", "PShort")) %>%
  tabyl(SepalLong, PetalLong, Species) %>%
  walk2(names(.), ~ print(kable(.x, caption = .y)))
```

**Comment by sfirke** [comment]
I think the `walk2` command above from @fernandovmacedo is a good solution.  For more see the discussion linked above https://github.com/yihui/knitr/issues/1981.  I don't plan to work on this more so I'm closing it as unplanned.
