### ISSUE TITLE
Add remove_empty for matrices?

### ISSUE THREAD

**Issue by jsta** [sfirke/janitor#215]
## Feature requests

I was surprised at the output of `remove_empty` when passed a matrix. It seems to return a vector rather than a trimmed matrix object:

```
mat <- matrix(c(NA, NA, NA, rep(0, 3)), ncol = 2, byrow = TRUE)

janitor::remove_empty(mat)

> [1] NA  0  0  0
```

Is adding functionality for matrices out of scope? If so, maybe it would be good to throw an error or warning if passed a matrix?

**Comment by billdenney** [comment]
@jsta, Can you please try the pull request I just made to see if it fixes your issue?

@sfirke, Rather than make it generic, I added a comma and `drop=FALSE`.  (Make sure that you get the second push rather than just the first one.)

**Comment by jsta** [comment]
@billdenney tested, your PR works for me. Only thing I see is that it might be good to mention matrices and other 2d structures in the function docs.

**Comment by sfirke** [comment]
thanks @jsta for reporting and for this additional advice to mention matrices in the docs, I added that.  Thanks @billdenney for the fix, that is way simpler than an S3 method.  I merged the PR, this is live.

Maybe a dumb Q: are there other 2d data structures that should get mentioned in the docs or tested for?  I only know of matrix and data.frame.
