### ISSUE TITLE
excel_numeric_to_date with include_time = TRUE can return 60 for seconds

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#217]
Split off from #216, won't get to this in the next patch release that CRAN is requesting.

Here's what I have as I started to address that floating point imprecision can cause `x %% 60` to return 60, which shouldn't be possible.
```

    # Because of floating point imprecision, total_sec %% 60 can return 60 for ret$sec
    # E.g., 86400 * (42001.1 %% 1) = 8639.99999987427145 when it should be 8640, then it %% 60 = 60
    # Presumably ret$min could also be 60
    # The following code block addresses situations where seconds or minutes are 60
    # See https://github.com/sfirke/janitor/issues/216
    if(ret$sec == 60){
      ret$min <- ret$min + 1
      ret$sec <- ret$sec - 60
    }
    if(ret$min >= 60){
      ret$hour = ret$hour + 1
      ret$min = ret$min - 60
    }
...
```
But the cascading changes here are massive.  Say it was 23:59:60 on February 28th.  That should probably be represented as the identical 00:00:00 on March 1st (if not a leap year).  The method I have above of manually incrementing each unit is too tedious.

I welcome thoughts - does anyone have a solution to convert `07:00:60` to `07:01:00` in an elegant, accurate way?  And how if at all is it a problem to currently output `07:00:60`?

**Comment by sfirke** [comment]
One test:
```
  expect_equal(excel_numeric_to_date(42001.1, include_time = TRUE),
               as.POSIXlt("2014-12-28 02:24:00"),
               info = "60 seconds gets converted to 0 seconds, +1 minute")
```

**Comment by sfirke** [comment]
@billdenney - would love your take on this at some point, though not urgent.  CRAN is requesting I submit a new version to address a dependency issue, I will ship with this unaddressed.

**Comment by billdenney** [comment]
What do you think about the pull request I just made.  It tries to ensure that the date number is an integer and that the hours, minutes, and seconds are handled earlier and hopefully more consistently.  I *think* that it should work for rounding around day integers, too, but it's not clearly the right way to manage rollover around a date.

For simplicity, we could not support sub-second resolution from Excel.  Given that the precision of floating point numbers from Excel is never great, it doesn't seem like a bad solution to me.

A more correct implementation of handling floating point imprecision around dates could be to determine if adding `.Machine$double.eps` causes an integer rollover, then it should be the next day.

**Comment by billdenney** [comment]
As I was thinking about it more, I thought that testing for within 0.001 sec seemed like the right solution.  I updated the code for that.  It's now dense with handling the sub-second resolution and possible rollover, but it should be correct for all but scenarios when the user wants a time accurately represented within the same day at a time after 23:59:59.999.

In my mind, if a user wants a time like 23:59:59.9999 (note the 4th 9), then the Excel date format isn't the right solution.

**Comment by sfirke** [comment]
Did you push the commit you refer to above with "I updated the code for that"?  It sounds good but I don't see it on the PR, just one commit over in #218 .

One test we can add, based on current inappropriate performance, is:
```
> excel_numeric_to_date(42000.999999, include_time = TRUE)
[1] "2014-12-27 23:59:60"
```
Should be 2014-12-28 00:00:00, which your revised code (the first commit at least) correctly produces.

**Comment by billdenney** [comment]
For some reason the second commit took some time to find its way to the pull request.  It should be there now (https://github.com/sfirke/janitor/pull/218/commits/ba95da704fd115c870e8e6b848bec06ef0c92273).
