### ISSUE TITLE
Feature Request: Drop Single-Value Columns

### ISSUE THREAD

**Issue by billdenney** [sfirke/janitor#222]
I often receive data where many of the columns may be a single value.  It's helpful find the information of interest by dropping all columns that only have a single value.  Would you be interested to include this feature in `janitor`?

``` r
interesting_cols <- function(x, ...) {
  mask_boring <-
    sapply(x,
           FUN=function(y) all(y %in% y[[1]]))
  boring <- x[1,mask_boring]
  ret <- x[,!mask_boring]
  attr(ret, "boring") <- boring
  ret
}
```

**Comment by billdenney** [comment]
A naming idea:  Rather than `interesting_cols` (as I named it in my private library), `remove_static` would match better with `remove_empty` to keep the API consistent (with the attribute renamed to "static" instead of "boring").

**Comment by sfirke** [comment]
I like this idea as an addition!  What about `remove_constant_cols` or `remove_static_cols` - since it would only apply to columns?  Maybe more obvious what that does.  Or `remove_constants`.

In your code above, what purpose does the attribute code serve?

**Comment by billdenney** [comment]
The attribute lets me look at the things that were removed in case knowing what they were is also of interest.

I'll make a PR with `remove_constant()` also giving it a `which` argument allowing it to work on both columns and rows so that it has identical semantics to `remove_empty()`.  I don't use the rows option almost ever, but it seems to be nice and parallel in use cases that way-- and I assume that someone would ask for rows were we to have a columns-only version.

**Comment by billdenney** [comment]
... actually, on a bit of further consideration, I'll make a `keep_constant()` function, too, and not add the attribute in `remove_constant()`.

**Comment by jzadra** [comment]
Just something to consider - this functionality might be useful in a grouped tibble.  For instance if a column is constant within all groups but not between them.

Thanks,

Jon

--
Jonathan Zadra, PhD
Director of Data Science
Sorenson Impact Center
David Eccles School of Business, University of Utah
(801) 581-4815
jonathan.zadra@sorensonimpact.com
www.sorensonimpact.com
On Feb 19, 2019, 10:53 AM -0700, Bill Denney <notifications@github.com>, wrote:
> ... actually, on a bit of further consideration, I'll make a keep_constant() function, too, and not add the attribute in remove_constant().
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

--

**Comment by billdenney** [comment]
@jzadra, That is a good idea though implementation gets a bit hairy.  (Mainly, I don't know how to operate on grouped tibbles outside of the full dplyr/tibble universe.)  I'll make the implementation as an S3 generic so we can easily extend it to grouped tibbles.

**Comment by sfirke** [comment]
I'm not sure if the utility of `keep_constant` is worth making it its own function, adding one more thing to the namespace and documentation.  Maybe we could include the simplest command to mimic `keep_constant` - it might be code that says `x deselect the columns in remove_constant(x)` - in the documentation for `keep_constant`.   It would say "if you want to examine the columns that were removed, run ...".

And as to `remove_constant(rows)` - I agree this is a very rare use case compared to columns.  The only thing I can think of is if someone formatted a separating row in Excel that was `----------------` ?  What is another plausible case of the same value repeating across a column and it's wrong?  I wonder if it's worth implementing.

**Comment by billdenney** [comment]
Ok, I’ll drop `keep_constant()`.  The simplest command I can imagine to mimic its functionality would be something like the following, and I’ll add it to an example in the documentation (typed into my phone, so please ignore minor bugs, they won’t exist in the actual code):

```r
data %>%
  select_at(.vars=setdiff(names(.), names(remove_constant(.)))
```

I also agree that removing constant rows is pretty unlikely, and in my experience, it is something like what you suggest.  That example is reasonably handled by `na_if()` and `remove_empty()`.  With that, I’ll drop the `which` argument, too.

**Comment by sfirke** [comment]
+1 to both of those.  Yes to `setdiff(names(`, that was the approach I was thinking of and couldn't remember.

And we are in agreement re: being able to handle `-----------` in other ways.  Having such a row would impair data ingestion as `readxl` would think they are all character columns; in that case, the unwanted value could be supplied to `na = "-"` and then as you note `remove_empty` would do it from there.
