### ISSUE TITLE
Should excel_numeric_to_date return POSIXct?

### ISSUE THREAD

**Issue by billdenney** [sfirke/janitor#225]
This is related to tidyverse/dplyr#3735

POSIXlt doesn't play well with the `tidyverse`, it appears, as described in the issue above.  While the construction of the date-time object in `excel_numeric_to_date` benefits from the flexibility of assignment within POSIXlt, should we then convert it to POSIXct to make it more usable within the broader R ecosystem?

(I think that `lubridate` uses POSIXct for unusability issues, too.)

**Comment by dan-fahey** [comment]
Thank you for https://github.com/sfirke/janitor/pull/214 btw! Very handy. If the output of `excel_numeric_date` was POSIXct I'd agree it would be more convenient as currently it must be passed through `as.POSIXct' to avoid the `is of unsupported class POSIXlt` errors.

**Comment by sfirke** [comment]
Great let's do this. Appreciate the multiple voices and references. I will
be back to R development in the coming weeks, sorry to have been less
responsive recently.

**Comment by billdenney** [comment]
@sfirke Having a baby does that!  :)

Both: There doesn't appear to be a way to create a POSIXct object without a timezone.  Given that Excel doesn't keep the time zone, which do you think is a better default:

Add a `tz` argument to `excel_numeric_to_date` which is passed to `as.POXIXct` and
1. Set it to ""?
2. Set it to "GMT" (so that daylight savings time is not applied)?

(I lean toward 1 for consistency with other date/time functions, but since we don't actually have the time zone in our source data, I wish there were a way to unset the time zone.)
