### ISSUE TITLE
What should excel_numeric_to_date do with user-provided invalid value of tz?

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#232]
Related to #225: right now if user provides an invalid timezone like "PST" they'll see a warning:

> In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'PST'

But then the resulting values have timezone = `GMT`.  I think `""` is a safer way to fail than GMT, and either way I think it should print an error message along the lines of, `"The value "PST" provided to the tz  argument is not a timezone recognized by R. The resulting dates will have the blank timezone value ''."`

**Comment by sfirke** [comment]
FYI I have a placeholder for this test that should be updated/removed when the decision & code are finalized:
```
  # this test should be written:
  # providing a bad timezone value defaults to blank tz value "" and throws warning
  # Then delete prior test as it will fail
```

**Comment by sfirke** [comment]
@billdenney I've added you as a collaborator for this repo so you can push to the repo, close issues, etc.  If/when you accept then I can assign this to you 📬

**Comment by billdenney** [comment]
The behavior is documented in the `as.POSIXct()` documentation: https://stat.ethz.ch/R-manual/R-devel/library/base/html/as.POSIXlt.html

My first thought on this is that we should request a more descriptive warning message upstream.  The current warning could be more descriptive to indicate what will happen to the requested timezone in case it is invalid.  If we try to handle the result, then we will have a lot more work to maintain it correctly (as in we will have to carefully track what happens upstream).

One option could be to test what the timezone is just before output and provide the more descriptive warning then (though the user would get duplicated warnings which may be difficult to interpret).

**Comment by sfirke** [comment]
Oof.  The build is failing on Linux because unlike on Windows, where I filed this issue, an invalid timezone is assigned without warning.  I ran the test on my Ubuntu machine and sure enough:
```
> excel_numeric_to_date(43001.11, include_time = TRUE, tz = "nonsense")
[1] "2017-09-23 02:38:24 nonsense"
```
Thanks for the link to the documentation.  From there I got to: https://stat.ethz.ch/R-manual/R-devel/library/base/html/timezones.html  And reading that it's system-specific, combined with the taste of the current test failing on Ubuntu but not Windows, make me think we can just let the function work as is and it's up to the user to specify a valid timezone, and close this.

What do you think?

**Comment by billdenney** [comment]
I agree to leave it to the user and with default R behavior.  Taking on time zones is a massive undertaking that is more think fits the intent of `janitor`.
