### ISSUE TITLE
Add further reading references to 'tz' argument of excel_numeric_to_date

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#233]
Related to #232, I think we should provide a reference link in the documentation for the `tz` argument that would allow users to read more about valid timezones and see a list of them.  I found my way to `https://data.iana.org/time-zones/tz-link.html` but would like something simpler. A list of common timezones on a website might be more useful to the typical user than shell commands to download a tarball.

Maybe two links, the one I have above for further / more advanced reading and a simpler one with list of common timezones?

**Comment by billdenney** [comment]
I have a similar response here that unless we want to handle the complexity of timezones internally (which I think is better left to other functions and packages), we would be better off linking to the functions that handle the timezones for us.

To get the list, we can suggest `base::OlsonNames()`, and to get the current time zone, we can suggest `base::Sys.timezone()`.  That would be my preference.

**Comment by sfirke** [comment]
I like your fix: add to the documentation of the `tz` argument that they can see a list of timezones with `base::OlsonNames()` and their current timezone with `base::Sys.timezone()`.
