### ISSUE TITLE
remove_empties strings

### ISSUE THREAD

**Issue by gvdr** [sfirke/janitor#234]
## Feature requests

Hi, new to the project. I wrote a quick modification to `remove_empties()` to allow the removal of columns or rows which entries are only _empty_ strings (i.e. strings of length 0, ''). This often appears in place of missing values when reading CSV or other rectangular data, and are not captured by `is.na()`.

The modification to the code is minimal, speed is not compromised if the option is set to FALSE, and it is still really fast when option is set to TRUE.

Let me know if it of interest and I create the pull request.

**Comment by gvdr** [comment]
Yes, it can be easily done in various ways :-) If there's interest in having it at as a quick option for `remove_empties()` I'm happy to contribute it, otherwise no worries :+1:

**Comment by sfirke** [comment]
So sorry for never responding to this.  I appreciate the idea and offer to help!  However I agree with Bill that the sequence of other functions is obvious and quick enough that it doesn't warrant including another argument to `remove_empty`.  `naniar` has a single function that can precede `janitor::remove_empty()`, `replace_with_na_all`.

`naniar::replace_with_na_all(dat, ~.x == "")`
