### ISSUE TITLE
clean_names: Wrong function name reference in example

### ISSUE THREAD

**Issue by KyleHaynes** [sfirke/janitor#236]
https://github.com/sfirke/janitor/blob/e3fee8a02b50eae4cf8b624bee5434ebdb5b5fbb/R/clean_names.R#L37

Should be `read_excel` or `read_xlsx`?

**Comment by sfirke** [comment]
Great catch, it should be `read_excel`!  Would you like to submit this change as a pull request - it's your contribution - or would you prefer I do it?

**Comment by KyleHaynes** [comment]
Hi Sam,

I'd generally just say you do it, though I do want to become more familiar with how GitHub works. 

Currently at work, will do this in 5-10 hours if that suits?

Cheers

**Comment by sfirke** [comment]
This could be an ideal learning opportunity for using GitHub.  Here the steps would be roughly:

1. Fork the repository (make a copy of it)
2. Clone a local copy
3. Make the edit to the .R file
4. Run `devtools::document()` to update the corresponding .md documentation file
5. Create a pull request from your repository to this one (from `KyleHaynes/janitor` to `sfirke/janitor`)

Please let me know if you have any questions.
