### ISSUE TITLE
excel_numeric_to_date throws error when input is large integer

### ISSUE THREAD

**Issue by hideaki** [sfirke/janitor#241]
## Bug reports
excel_numeric_to_date throws error when input is integer.

```r
excel_numeric_to_date(42370L)

# Error in if (any(mask_day_rollover)) { : 
#   missing value where TRUE/FALSE needed
# In addition: Warning message:
# In date_num * 86400L : NAs produced by integer overflow
```

**Comment by sfirke** [comment]
Thanks for filing this bug!  I see it's an overflow error which explains why this works: `excel_numeric_to_date(20004L)` with a smaller integer.

@billdenney would you be able to take a look at this?

**Comment by billdenney** [comment]
I'm on it.

Since R only has 32-bit signed integers by default, and the default double has 53 bits of precision, I'm going to do something almost identical to what they have done in exploratory-io/exploratory_func#491.  I don't think it's worth it to use the `bit64` library for this change.
