### ISSUE TITLE
Feature Request: excel_numeric_to_time

### ISSUE THREAD

**Issue by billdenney** [sfirke/janitor#245]
We currently have `excel_numeric_to_date()` to assist with converting dates and datetimes to POSIXct objects.  Can we create a similar function for `excel_numeric_to_time()` or perhaps more accurately `excel_time_to_numeric()`?

Excel stores times in a format as a fraction of a day, and an issue that I commonly have when opening an Excel file with times is that they are not consistently read correctly (this is also related to tidyverse/readxl#504).

In files that I read, the person providing the file often mixes multiple formats accidentally, so that when read in, I get a mixture like the following:

```r
c("9:04AM", "14:35", "0.395833333333", "1899-12-31 08:05")
```

The issue that I have is usually related to the mixture of formats due to imprecise data entry.  I think it would be a good pairing with the `excel_numeric_to_date()` function to have a function to help handle times.  The interface I was thinking of is below.  The input would be any of the formats above:

* a fraction between 0 (inclusive) and 1 (exclusive) that may be a character string.
* Time with AM/PM (must have AM/PM case insensitively at the end)
* 24-hour time
* A POSIXlt or POSIXct object on the day "1899-12-31"
    * Or a character string that looks like a POSIXlt/POSIXct object from this day, notably the string starts with "1899-12-31 " and then has a 24-hour time.

The return value would be a the number of seconds in the time (a value >=0 and <86400).  Another option for output could be a lubridate duration object (but that would require lubridate as a dependency).

```r
excel_time_to_numeric(time_value, round_seconds=TRUE)
```

If interested, I can make a PR.

**Comment by sfirke** [comment]
Do you think aspects of this and #246 are still relevant in light of `convert_to_datetime` having been implemented?  The one thing that jumps out at me is handling things like "8:00 AM" -- but I don't know how that would fit in with `convert_to_datetime` and I like that `convert_to_datetime` handles the date part as well.

**Comment by sfirke** [comment]
(I'm cleaning up PRs - sorry for letting this one linger so long 😔 )

**Comment by billdenney** [comment]
I think that the preferred method here would be to add a `convert_to_time()` function that would perform similar work to `convert_to_date()`.
