### ISSUE TITLE
Test for failure of clean_names.sf if `sf` pkg is not present

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#253]
This is a gap in test coverage from #249.  But maybe it's not even worth rigging up a test and instead I should just exempt from coverage?  Because how could `clean_names.sf` be invoked -- only on an `sf` object -- without the `sf` package present to create the sf object?

This is the line that doesn't get tested:

>"Package \"sf\" needed for this function to work. Please install it."

**Comment by jsta** [comment]
I agree with exempting from coverage.
