### ISSUE TITLE
Add chi square test for tabyl objects?

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#255]
To offer all the functionality of table(), would it be useful to be able to run a chisq.test() on a tabyl?  Would other statistical tests be useful?

Might be almost this simple, no?
```
chisq.test.tabyl <- function(dat, ...){
  # should check if input is two-way tabyl
  dat %>%
    dplyr::select(-1) %>%
    as.matrix() %>%
    chisq.test(...)
}
```

**Comment by juba** [comment]
I just ran into the `chisq.test` incompatibility problem just before seeing this issue. So I think this would be a really good idea.

Your implementation should work, I don't think you even have to convert to a matrix.

Thanks !

**Comment by dgkeyes** [comment]
I would love to see chisq.test() implemented in janitor!

**Comment by sfirke** [comment]
Alright this has the green light to implement.  Anyone is welcome to write a pull request along the above lines, if you plan to do so you can post here to claim it.

And are there any other statistical tests that we should also consider?

**Comment by juba** [comment]
I just created a PR to implement this. If it is accepted, I may also create one for the `fisher.test` function, if You think it could be useful.

**Comment by sfirke** [comment]
Thank you @juba !  I took a break from the computer but am back and will review this, I expect this week.

**Comment by svgsstats** [comment]
Thanks for sharing this.   I also just recently ran into this issue teaching an intro stats course.  Had my students used to constructing contingency tables with tabyl as opposed to table only to realize that I have to go back to table with the chi-square test.

**Comment by sfirke** [comment]
Ack sorry I still haven't reviewed and merged the PR!  I have a lovely block of time next week and will put this at the top of the list for janitor.
