### ISSUE TITLE
clean_names throws error depending on package loading order

### ISSUE THREAD

**Issue by jsta** [sfirke/janitor#256]
I get an error if I run:
```
library(sf)
library(janitor)
```
> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
Error: package or namespace load failed for ‘janitor’:
 .onLoad failed in loadNamespace() for 'janitor', details:
  call: get(genname, envir = envir)
  error: object 'clean_names' not found
Execution halted

but no error if I run:

```
library(janitor)
library(sf)
```

**Comment by sfirke** [comment]
Anyone know what causes this & how to properly address it?

**Comment by jsta** [comment]
I get no error if I comment out https://github.com/sfirke/janitor/blob/master/R/zzz.R#L4. The package passes checks and tests without this line as well. Maybe I'm missing something but I think we can drop `register_s3_method`? @JosiahParry

**Comment by JosiahParry** [comment]
Interesting. I came here because I just started experiencing the same problem. I'm not sure how to solve it. Hopefully @jsta your solution works? I apologise for creating this problem!

**Comment by sfirke** [comment]
Thanks @jsta for reporting and for the PR to close it.  I am pleased that `clean_names` covers `sf` objects but because I never use `sf` myself I am dependent on you to report issues like this and to fix them.  I appreciate it!
