### ISSUE TITLE
Weighted data?

### ISSUE THREAD

**Issue by chfranklin** [sfirke/janitor#257]
## Feature requests

Integrating weights for crosstabs would be helpful. Survey data is virtually always weighted and is a very common application for crosstabs. Without a weight option, tabyl is not useful for survey analysis. Otherwise I’d be very excited to use the janitor package. Thanks! (If I’ve missed this feature, my apologies.)

**Comment by sfirke** [comment]
I appreciate the feature request.  Have you tried out the `survey` package or its tidy version, `srvyr`?  Here is a vignette comparing them: https://cran.r-project.org/web/packages/srvyr/vignettes/srvyr-vs-survey.html  They are made for survey data and I believe do a nice job with weighted crosstabs (though I haven't used personally).

Given the existence of those packages I'm not planning to implement weighting in janitor tabulations.

**Comment by chfranklin** [comment]
Fair enough. I appreciate the package and your work on it.

Charles Franklin
Director Marquette Law School Poll
Charles.franklin@marquette.edu
608-235-1960 (cell)

@pollsandvotes
Charles@pollsandvotes.com
