### ISSUE TITLE
Feature request:  names_to_row()

### ISSUE THREAD

**Issue by eteppo** [sfirke/janitor#259]
Hey!

First of all, janitor has been of great help so thanks to all the developers.

Working on a messy excel-file I noticed that I needed to do the opposite of `janitor::row_to_names()`. Something like `. %>% bind_rows(colnames(.))` feels a bit clunky, just like something like `. %>% set_colnames(. %>% extract(3, ) %>% as.character())` is for `row_to_names()`.

**Comment by jzadra** [comment]
The `tibble` package (part of tidyverse) has these functions.  Is this not what you are looking for?

`rownames_to_column(df, var = "rowname")`

`rowid_to_column(df, var = "rowid")`

`column_to_rownames(df, var = "rowname")`

**Comment by eteppo** [comment]
Thanks for the reply. 

Not exactly, it seems like the only function that is missing is indeed `colnames_to_row()` that I was looking for. I can see why though, it's not a common operation.

`janitor::row_to_names()` is basically `row_to_colnames()` in the `tibble` parlance. 

So with these functions you can move between rownames and columns both ways but between colnames and rows only one way if I'm not totally confused.

**Comment by sfirke** [comment]
The only use case I can think of is if the spreadsheet/data source has no names, and data in the first row.  Then you'd need to do this, except in that case I'd specify `col_names = FALSE` to the data ingest function like `readr::read_csv()`.  What other use case might there be for putting the column names into the data.frame?

**Comment by eteppo** [comment]
You are probably right, and I guess this function would be mainly for completeness (or what that's called when you cover all possible operations without expecting much usage). 

I think my use case was that I needed to transpose my dataset with `t()` so that the column names become the first column in some way. My only idea back then was to make the names the first row and do that. `gather()` and `spread()` from the tidyr-package crashed.

**Comment by sfirke** [comment]
Hrm.  That is an interesting use case, I often run into unusual and vexing problems when I"m using `t()`.  That function is like dark magic or something, but when I need it I need it.

I'm going to close this for now because I think this function wouldn't be very widely used.  But if you ever document this example use case on a blog post or the RStudio discussion forum or elsewhere, please comment on this issue as I'd be interested in weighing in with solutions and seeing what others propose.
