### ISSUE TITLE
clean_names on grouped data results in corrupted groupings

### ISSUE THREAD

**Issue by CerebralMastication** [sfirke/janitor#260]
Thanks for a GREAT package! 

I've noticed that when I run `clean_names` on a grouped data frame, if it renames one of the groupings then things break. The break happens because the attribute `vars` which is set by `group_by` maintains the old spelling while the underlying data frame no longer has a column with that name. 

It seems that `clean_names` should either check the grouping or possibly use the `rename` function from `dplyr` which correctly manages the grouping names. 

Example:

``` r
library(tidyverse)
library(janitor)

df <- tibble(Letters = rep(letters[1:2],3), 
             numbers = 1:6
)

# rename the column using `rename`
df %>%
  group_by(Letters) %>%
  rename(letters = Letters) %>%
  filter(letters == "a")
#> # A tibble: 3 x 2
#> # Groups:   letters [1]
#>   letters numbers
#>   <chr>     <int>
#> 1 a             1
#> 2 a             3
#> 3 a             5

# rename the column using `clean_names`
df %>%
  group_by(Letters) %>%
  clean_names() %>%
  filter(letters == "a")
#> Error in filter_impl(.data, quo): Column `Letters` is unknown
```

**Comment by Tazinho** [comment]
Yes, there is currently no handling for that. As a workaround u might also use rename_all(make_clean_names).

**Comment by CerebralMastication** [comment]
Thanks for the tip. I have other cases where `make_clean_names` might come in handy too! I had overlooked that function.

**Comment by sfirke** [comment]
Thanks for the reprex bug report!  I agree that using dplyr::rename() in `clean_names()` should address this issue without otherwise changing the behavior of the function.  I'll give it a shot.

**Comment by sfirke** [comment]
Doh I looked at this yesterday and missed where @Tazinho said to use `dplyr::rename_all()` which does seem like a simple approach (I was thinking of plain `rename` and that seemed more complex).  Then maybe this is easy.  I just put v1.2.0 on CRAN yesterday but if someone is up for sending a PR for this change to `clean_names()`, it would get us going toward 1.3!

**Comment by sfirke** [comment]
I still think this is worth fixing but FWIW I don't get an error in the latter scenario above.  Instead I get a result, with the Group name still uppercase as stated by dplyr but the col name lowercase:
```
df %>%
  group_by(Letters) %>%
  clean_names() %>%
  filter(letters == "a")
#> # A tibble: 3 x 2
#> # Groups:   Letters [1]
#>   letters numbers
#>   <chr>     <int>
#> 1 a             1
#> 2 a             3
#> 3 a             5
```
Not sure how bad that is or if there are other consequences - but no reason not to fix.

**Comment by sfirke** [comment]
I have a branch that implements `rename_all` and it works on a data.frame like `iris` but not on this one from the Janitor vignette with gnarly names: https://github.com/sfirke/janitor/blob/clean_names_of_group_vars/tests/testthat/test-clean-names.R#L176-L180

Specifically if you want to try it out in your console without installing anything:
```
test_df <- as.data.frame(matrix(ncol = 6))
  names(test_df) <- c("firstName", "ábc@!*", "% successful (2009)",
                      "REPEAT VALUE", "REPEAT VALUE", "")
test_df %>% rename_all(make_clean_names) 
```
> Error in is_symbol(expr) : argument "expr" is missing, with no default

But this works: `iris %>% rename_all(make_clean_names)`.  Anyone have an idea of what's happening here?

**Comment by sfirke** [comment]
**Restating the problem**

Challenge: `clean_names` must both handle duplicated names AND preserve grouping.  It sees both kinds of input.

Here's a data.frame that has both:
```
dat <- data.frame(
  a = 1:5,
  b = letters[1:5],
  c = rep(NA, 5)
)
names(dat)[3] <- "b"
dat <- dat %>%
  group_by(a)
```
This way loses grouping:
```
dat %>%
  clean_names()
```
And this way fails on duplicated names:
```
dat %>%
  rename_all(make_clean_names)
```

I had hoped that last chunk would run under tidyselect 1.0.0, but it appears not to.  I will confirm that, then I have a workaround:

- check if grouped, note which columns
- ungroup
- call clean_names
- reset grouping to the same columns

Not elegant but I think it would work.  And using column indices with `group_by_at()` should be straightforward.

**Comment by sfirke** [comment]
Apparently this will be fixed in dplyr 1.0.0, here someone showed proof: https://gist.github.com/maurolepore/6558292c5003a15e246a88091c307b65

**Comment by sfirke** [comment]
This now appears to be fixed, without me doing anything.  I didn't understand how this could work but I think it's this line, from the dplyr 1.0.0 release notes:

"Grouped data frames now have names<-, [[<-, [<- and $<- methods that re-generate the underlying grouping."

So when `setNames` says `names(object) <-` that calls the grouped.df method which keeps things tidy?

In which case, thanks tidyverse devs, we can close this issue after I add tests (to check against future breakage).  Can anyone else confirm this should be closed?  Tests already written on this branch: https://github.com/sfirke/janitor/compare/clean_names_of_group_vars

```
x <- data.frame(CAPS = 1) %>% group_by(CAPS)
x

# A tibble: 1 x 1
# Groups:   CAPS [1]
   CAPS
  <dbl>
1     1

setNames(x, "caps")
# A tibble: 1 x 1
# Groups:   caps [1]
   caps
  <dbl>
1     1
```

**Comment by billdenney** [comment]
It works for me, too.  The only other change that we may want to consider is requiring dplyr >=1.0.0 in the DESCRIPTION file.

**Comment by sfirke** [comment]
Thanks Bill. I think I will require dplyr >= 1.0.0, as it also means I could remove this now-unnecessary call to `clean_names` in `adorn_totals("col")` https://github.com/sfirke/janitor/blob/master/R/adorn_totals.R#L92
