### ISSUE TITLE
Specify text for adorn_total()

### ISSUE THREAD

**Issue by StephieLaPugh** [sfirke/janitor#263]
Hi there, 

I am loving this package, and I figured out the workaround for converting columns to characters (formatting with scales functions also works) before adding adorn_totals(), and that works great. (Though I'd still vote for being able to specify columns to sum in the adorn_totals() arguments directly.)

I would also like to be able to enter my own text instead of "Total".  "Total" is great as the default, but it would just be nice to be able to use custom text because clients want what they want, don't they? ;-)

Thanks!

**Comment by sfirke** [comment]
thanks @StephieLaPugh for suggesting this and @daniel-barnett for implementing!  This also makes the package slightly friendlier to users working in a language other than English.

**Comment by daniel-barnett** [comment]
Great news @sfirke!

**Comment by StephieLaPugh** [comment]
Sweet! Thanks so much!
