### ISSUE TITLE
tabyl_type, row, column, index attributes for 3way tabyls

### ISSUE THREAD

**Issue by dpashouwer** [sfirke/janitor#267]
Similarly to the attributes of a 2way tabyl ($tabyl_type, $var_names$`row`, $var_names$col), it'd be useful to have similar attributes for 3way tabyls.

```r
# example 3way table

(ex_3way_tabyl <- mtcars %>%
+     tabyl(cyl, gear, vs))

$`0`
 cyl  3 4 5
   4  0 0 1
   6  0 2 1
   8 12 0 2

$`1`
 cyl 3 4 5
   4 1 8 1
   6 2 2 0
   8 0 0 0

# attributes for the example 3way table

ex_3way_tabyl %>% attributes()

$`names`
[1] "0" "1"
```
Maybe...
attributes(ex_3way_tabyl)$tabyl_type == "three_way"
attributes(ex_3way_tabyl)$'row' == "cyl"
attributes(ex_3way_tabyl)$col == "gear"
attributes(ex_3way_tabyl)$index == "vs"

**Comment by sfirke** [comment]
It was easy enough to store these attributes in the 3-way tabyl list.  But then they print to the console, which is highly undesirable.  I don't understand a way to retain the attributes in the object, but not have them printed.  I tried declaring a new class `tabyl_3way` and writing a print method, see the commits linked above from a dev branch - but I'm not having luck.

Will put this on hold until/unless someone can advise on how to proceed here.

**Comment by sfirke** [comment]
Closing this as unplanned.  It looks like maybe it could be done with a custom print method, ala https://stackoverflow.com/questions/66447164/how-to-create-a-printing-method-that-doesnt-print-attributes-without-making-a, but I don't have the cycles to implement this and won't for the foreseeable future.
