### ISSUE TITLE
clean_names should support 'none' as a case option

### ISSUE THREAD

**Issue by andrewbarros** [sfirke/janitor#269]
The documentation for clean_names states:

> "parsed", "mixed", "none", "internal_parsing": less-common cases offered by snakecase::to_any_case. See to_any_case for details.

but the arguments in the function signature are 
`
function (dat, case = c("snake", "lower_camel", "upper_camel", 
    "screaming_snake", "lower_upper", "upper_lower", "all_caps", 
    "small_camel", "big_camel", "old_janitor", "parsed", "mixed")) 
{
    case <- match.arg(case)
...
`
This makes calls with case = 'none' throw an error.

Reprex:
```r
janitor::clean_names(mtcars, case = 'none')
#> Error in match.arg(case): 'arg' should be one of "snake", "lower_camel", "upper_camel", "screaming_snake", "lower_upper", "upper_lower", "all_caps", "small_camel", "big_camel", "old_janitor", "parsed", "mixed"
```

It's a rare case but I'd like to use the clean_names functionality for removing problematic characters but not touch the case. 

I have a PR prepared if this is reasonable.

**Comment by sfirke** [comment]
Great catch.  Yes, "none" should be supported as you note it is supposed to
be.  I would welcome a PR, thank you.  If you're up for it could you
include unit tests and update the NEWS.md in your PR?

**Comment by sfirke** [comment]
Thanks Andrew!  Lucky commit 666 😈  
![image](https://user-images.githubusercontent.com/7569808/52757346-5d82c680-2fd2-11e9-8ee2-b9ee965fc6c7.png)
