### ISSUE TITLE
Feature Request:3-way with subtotals

### ISSUE THREAD

**Issue by pflick** [sfirke/janitor#275]
Just started using janitor for my reports.  I do a lot of reports in excel and am trying to replace these with R.  The 2-way tabyl works great but I have a requirement for a 3 way with subtotals (using Excel's percent of parent row).  I have been able to create a 2-way that has the subtotals and then interweave this with the 3-way to get the final.  Is there a better/easier way to do this? Thanks for the package!

```r
library(janitor)
library(dplyr)
humans <- starwars %>%
  filter(species == "Human")


# first create the 3-way that creates a list of dataframes
tbl3way<-humans %>%
  tabyl(hair_color, eye_color,gender) %>%
  adorn_totals("col") %>% # adds the total
  adorn_percentages("col") %>%  # percent by column
  adorn_pct_formatting(digits=0) %>%
  adorn_ns() %>%
  adorn_title("combined")

tbl3way

# next create the subtotals 
tbl2way<-humans %>%
  tabyl(gender, eye_color) %>%
  adorn_totals(where=c("row","col")) %>% # adds the total
  adorn_percentages("col") %>%  # percent by column
  adorn_pct_formatting(digits=0) %>%
  adorn_ns() %>%
  adorn_title("combined")

tbl2way

# now interleave them
theNames<-names(tbl2way)
finalTbl<-data.frame(stringsAsFactors=F)
for (i in 1:(nrow(tbl2way)-1)) {
  finalTbl<-rbind(finalTbl,setNames(tbl2way[i,],theNames))
  tbl1<-tbl3way[i][[1]]
  for (j in 1:nrow(tbl1)) {
    finalTbl<-rbind(finalTbl,setNames(tbl1[j,],theNames))
  }
}
finalTbl<-rbind(finalTbl,setNames(tbl2way[nrow(tbl2way),],theNames))
finalTbl
```

**Comment by sfirke** [comment]
Thanks for the nice note and example :smile: I don't know of a better way to do this with janitor or another package, this exceeds what janitor can and could do.  My only idea for improvement would be removing the loops; maybe you could `split` - or there's a tidyverse verb for that now I think? - the 2-way tabyl, then somehow interweave the two lists and `bind_rows` them, to avoid the loops.
