### ISSUE TITLE
clean_names() generates RStudio diagnostic warning when no arguments are provided

### ISSUE THREAD

**Issue by jzadra** [sfirke/janitor#279]
When you pipe a table to clean_names, it creates a diagnostic warning in RStudio: "Warning: argument 'case' is missing with no default."

However, the default is "snake".  Somehow RStudio is missing that fact, and I"m not sure whether it's an RStudio problem or a `janitor` problem.

![image](https://user-images.githubusercontent.com/25590353/54147745-69f31700-43f8-11e9-8c5f-20f5722bcccf.png)

**Comment by sfirke** [comment]
That one is new to me.  What version of RStudio are you running?  I wonder
if this is a change in a newer version, or if there's a setting that is
different from mine, as I can't replicate this.  I agree it's not desirable
behavior.

**Comment by jzadra** [comment]
So I am using a preview release: `1.2.1206`.  But I'm fairly certain it was happening to me before on the stable release.  I checked on a colleagues computer and it did not happen to her.

Also, the RStudio setting that controls this is in Global Options > Code > Diagnostics > Check arguments to R function calls.

![image](https://user-images.githubusercontent.com/25590353/54152479-f0acf180-4402-11e9-806a-6d72c4ecfdd0.png)

**Comment by sfirke** [comment]
hey @jzadra - any more insights into this problem?  I wonder if we should close it as an RStudio issue and just re-open if it turns out to be janitor-specific.

**Comment by jzadra** [comment]
I had assumed this might be due to me using a preview release of RStudio and dropped it, however the problem persists in the stable release of 1.2 (I'm using 1.2.1335, and janitor 1.2.0)

**Comment by Moohan** [comment]
I get the same issue, using RStudio 1.1.456 and janitor 1.2.0.

Anything I can do to further help diagnosis?

**Comment by sfirke** [comment]
Hm.  I think this is an RStudio issue, perhaps https://github.com/rstudio/rstudio/issues/4585 ?  Seems like the same behavior as with `xtabs` there.  Though I don't see `clean_names()` and `make_clean_names()` using `missing()` so I'm not sure what **@jackwasey** suggests there completely nails the cause.

**Comment by billdenney** [comment]
I just tested this today, and it doesn't seem to be an issue anymore.  If it is still an issue for anyone, please reopen the issue.
