### ISSUE TITLE
Default bind_method for compare_df_cols - bind_rows too lenient?

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#293]
I made `"bind_rows"` the default `bind_method` for `compare_df_cols` because I, and most janitor users, are using the tidyverse so are doing row-binding with `dplyr::bind_rows`.

But right now I'm using `compare_df_cols` to compare data.frames, not for binding but just to see how they differ.  There are columns in X but not Y, and Y but not X; I'm interested in seeing those but `bind_rows()` doesn't return those as a mismatch.  `rbind` does however.

We could either switch the default method here in a subsequent release, or (less break-y) put a note in the description emphasizing that if you want missing columns to be treated as mismatches, specify `bind_method = "rbind"`.

**Comment by billdenney** [comment]
I'd lean toward a documentation update.

If you use `return="all"`, you also should get all the information (independent of bind method).  There are a few ways to the answer you're looking for.

**Comment by sfirke** [comment]
Yep, I'll just add a sentence in the documentation.  In practice I've been using `return = "all"`.

**Comment by billdenney** [comment]
Sounds good to me.

**Comment by sfirke** [comment]
I should have included a reprex above to be sure, but from where I stand now, this doesn't need attention.  `return = "all"` , the solution as you suggested, is the default option.  Maybe I was overriding it with `"mismatch"` which is when the `rbind` vs `bind_rows` option would matter.

Then I go to add something to that effect but in fact it already says:
```
with "rbind", columns missing from a data.frame would be considered a mismatch (as in \code{base::rbind()}.
```
I don't know what I was experiencing but I don't see any action to take here.
