### ISSUE TITLE
Feature request: adorn_totals for tibbles

### ISSUE THREAD

**Issue by ymer** [sfirke/janitor#298]
Adorn_totals is a nice function. But when it's run on a tibble it changes the data type, and information is lost.

**Comment by sfirke** [comment]
Could you provide a minimal example of what you're talking about, noting
what should happen instead?

**Comment by ymer** [comment]
```
library(tidyverse)
library(wakefield)
library(janitor)

df <- r_data_frame(20, id, height, died)
str(df$Died)
##  logi [1:20] TRUE TRUE FALSE FALSE TRUE TRUE ...

dfa <- df %>% adorn_totals()
str(dfa$Died)
##  chr [1:21] "TRUE" "TRUE" "FALSE" "FALSE" "TRUE" "TRUE" "FALSE" "TRUE" ...
```

I think the column should retain being a logical operator.

**Comment by sfirke** [comment]
Thanks.  That specificity helps.  The issue isn't whether the input is a tibble; it comes from the fact that `adorn_totals(where = "row")` has to add _something_ in the new last row of the table for the columns that are not numeric and thus can't be summed.  The default is `"-"` which then coerces the `Died` column to be a character.

The only fix that comes to mind would be that, if the fill value `NA` is provided, columns that are not numeric will get an `NA` in the totals row and retain their existing class.  So here `Died` would get a character `NA`.  Is that the behavior you'd be looking for?

**Comment by ymer** [comment]
Yes

**Comment by sfirke** [comment]
This is a good idea, just a low priority fix for me as I triage issues.  Community: anyone who can write code that puts NA in the Total row and respects the original column class (including factor levels) is welcome to open a pull request with the code.

**Comment by sfirke** [comment]
@hamstr147 if you're up for it, take a look at this error?  There's a test failing on Travis for the old version of R that seems like maybe a legit failure related to testing the preservation of Date class: https://travis-ci.com/github/sfirke/janitor/jobs/399538260

**Comment by sfirke** [comment]
Specifically these are the failing tests:
```
══ testthat results  ═══════════════════════════════════════════════════════════

[ OK: 615 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 2 ]

1. Error: supplying NA to fill preserves column types (@test-add-totals.R#367) 
2. Error: supplying NA as fill still works with non-character first col and numeric non-totaled cols (@test-add-totals.R#403) 

> test_check("janitor")

── 1. Error: supplying NA to fill preserves column types (@test-add-totals.R#367

'origin' must be supplied

Backtrace:

 1. janitor::adorn_totals(test_df, fill = NA)

 3. base::`[<-.data.frame`(...)

 5. base::`[<-.Date`(`*tmp*`, iseq, value = NA_real_)

 7. base::as.Date.numeric(value)

── 2. Error: supplying NA as fill still works with non-character first col and n

'origin' must be supplied

Backtrace:

 1. janitor::adorn_totals(...)

 3. base::`[<-.data.frame`(...)

 5. base::`[<-.Date`(`*tmp*`, iseq, value = NA_real_)

 7. base::as.Date.numeric(value)
```

**Comment by hamstr147** [comment]
I'm happy to take a look this weekend to see if I can fix

**Comment by hamstr147** [comment]
I had a look yesterday evening - I think this should be solved by just calling `as.Date(NA_real_, origin = "1970-01-01")` , which seems to make it pass the previously failing build. Before I raise another PR I'll test it using POSIX as well just to make sure
