### ISSUE TITLE
remove_constant doesn't work on tibbles?

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#312]
```
remove_constant(data.frame(A=c(1, 1), B=c(2, 2)))
#> data frame with 0 columns and 2 rows
remove_constant(tibble::tibble(A=c(1, 1), B=c(2, 2)))
#> # A tibble: 2 x 2
#>       A     B
#>   <dbl> <dbl>
#> 1     1     2
#> 2     1     2
```
I think this is failing in this way - would need to be fixed in both conditions of `na.rm`:
```
dat[, 13] %in% dat[1, 13]
```
This does not work on a tibble, but it does work on a data.frame.

**Comment by billdenney** [comment]
Did you test with a version where #308 is applied?  That should have fixed tibble-related issues.

**Comment by sfirke** [comment]
Ah in fact I was going my analysis on an older computer, this is probably
it, sorry about that!

**Comment by sfirke** [comment]
Oops false alarm on my part 😳
