### ISSUE TITLE
Percentages in all rows/columns, and Ns in total rows/columns?

### ISSUE THREAD

**Issue by cgthigpen** [sfirke/janitor#313]
In 2- and 3-way tables, would it be possible to add the ability to have percentages in all rows/columns _except_ in any row and/or column totals? The results for a 2-way table with only column totals and percentages by row would look like:

| Row Variable | Column Value 1 | Column Value 2 | Total |
| ------------- | ------------- | ------------- | ------------- |
| Row Value 1  | 25%  | 75% | 4 |
| Row Value 2  | 34%  |  66% | 6 |

Compared to the adorn_pct_formatting + adorn_ns approach, this seems cleaner to me, both visually and from a data manipulation perspective later on, if I wanted to use the tabyl in reporting or analysis.

**Comment by sfirke** [comment]
Hrm, because the 100% that would be there otherwise is kinda meaningless?  I see that.  I guess this would be an argument to adorn_totals, whether the total count should be left alone by subsequent adorns of percent, pct_formatting, n.  It's non-trivial to implement, as that would have to be stored as an attribute on the table.  But I think it's possible.  I probably won't prioritize this but am open to someone else implementing it and sending a pull request.  At any rate, thank you for the idea!

**Comment by sfirke** [comment]
Bah I thought a fix to #219 would address this, but only halfway.  You could do the column example like you have, but it wouldn't solve the bottom totals _row_.

**Comment by sfirke** [comment]
Update: this works great for leaving the total column alone!  It's a result of the `adorn_` functions now allowing for column specifications with `...`.  Here's an example:
```
library(janitor)
mtcars %>%
  tabyl(cyl, gear) %>%
  adorn_totals("col") %>%
  adorn_percentages("row",, -c(cyl, Total)) %>%
  adorn_pct_formatting(,,, -c(cyl, Total))
#>  cyl     3     4     5 Total
#>    4  9.1% 72.7% 18.2%    11
#>    6 28.6% 57.1% 14.3%     7
#>    8 85.7%  0.0% 14.3%    14
```
I did not implement the same thing to leave the totals _row_ alone.  That would require more code, where the user would specify in `adorn_totals()` that the row should remain unadorned and then the other `adorn_` functions would all have to be modified to check for that and respect it.  Lots of modification for a non-essential payoff.  I'm not ruling it out in the future which is why I just put my thoughts into writing :innocent: but I'm going to close this issue for now, satisfied with the column-wise success.

**Comment by cgthigpen** [comment]
Thank you!

**Comment by jzadra** [comment]
@sfirke I think we could use something like this for the totals row as well.

**Comment by jzadra** [comment]
@sfirke I wrote a quick function today that kind of deals with handling the totals row.  Granted it's not very flexible as far as options to selectively decide where to adorn the percentages, but it does clean up the output when you are wanting to `adorn_percentages` AND `adorn_totals` to both rows and columns, AND `adorn_ns`.

The typical output from doing this using current functions gives lots of non-informative "100%" percentages, over 100% values in some row totals, and also gives a percent for Grand Total that is a multiple of 100% * ncol:

``` r
require(tidyverse)
#> Loading required package: tidyverse
suppressPackageStartupMessages(require(janitor))
suppressPackageStartupMessages(require(knitr))

mtcars %>% 
  tabyl(gear, cyl) %>% 
  adorn_percentages("col") %>%
  adorn_totals("row", name = "Column Total") %>% 
  adorn_totals("col") %>% 
  adorn_pct_formatting() %>%
  adorn_ns() %>% 
  kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">gear</th>
<th style="text-align: left;">4</th>
<th style="text-align: left;">6</th>
<th style="text-align: left;">8</th>
<th style="text-align: left;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">9.1% (1)</td>
<td style="text-align: left;">28.6% (2)</td>
<td style="text-align: left;">85.7% (12)</td>
<td style="text-align: left;">123.4% (15)</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">72.7% (8)</td>
<td style="text-align: left;">57.1% (4)</td>
<td style="text-align: left;">0.0% (0)</td>
<td style="text-align: left;">129.9% (12)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">18.2% (2)</td>
<td style="text-align: left;">14.3% (1)</td>
<td style="text-align: left;">14.3% (2)</td>
<td style="text-align: left;">46.8% (5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Column Total</td>
<td style="text-align: left;">100.0% (11)</td>
<td style="text-align: left;">100.0% (7)</td>
<td style="text-align: left;">100.0% (14)</td>
<td style="text-align: left;">300.0% (32)</td>
</tr>
</tbody>
</table>

Here is a function that solves these issues.  The column totals show the percent of the column with the grand total as the denominator.  The row totals show the percent of percent of the row totals with the grand total as the denominator.  And the grand total shows 100%:

**NOTE THAT THIS REQUIRES THE NEW FUNCTION `rows_update()` from the upcoming dplyr 1.0** which is available in the current dev version (will be released as 1.0 May 15)

``` r
require(tidyverse)
#> Loading required package: tidyverse
suppressPackageStartupMessages(require(janitor))
suppressPackageStartupMessages(require(knitr))


adorn_everything <- function(dat, pct_direction = "col") {
  dat %>% 
    adorn_percentages(pct_direction) %>%
    adorn_totals("row", name = "Column Total") %>% 
    adorn_totals("col") %>% 
    adorn_pct_formatting() %>%
    adorn_ns() %>% 
    rows_update(y = slice(., nrow(.)) %>% 
                  pivot_longer(-1) %>% 
                  mutate(value = str_extract(value, "\\(\\d*\\)") %>% str_remove_all("\\(|\\)") %>% as.numeric) %>% 
                  mutate(total_temp = max(value)) %>% 
                  mutate(total_pct = value / total_temp,
                         total_pct = scales::percent(total_pct, accuracy = .1)) %>% 
                  mutate(Total = paste0(total_pct, " (", value, ")")) %>% 
                  select(1, name, Total) %>% 
                  pivot_wider(names_from = name, values_from = Total), by = colnames(.)[1]) %>% 
    mutate(Total = str_extract(Total, "\\(\\d*\\)") %>% str_remove_all("\\(|\\)") %>% as.numeric) %>% 
    mutate(total_temp = max(Total)) %>% 
    mutate(total_pct = Total / total_temp,
           total_pct = scales::percent(total_pct, accuracy = .1)) %>% 
    mutate(Total = paste0(total_pct, " (", Total, ")")) %>% 
    select(-total_temp, -total_pct) %>% 
    rename("Row Total" = Total)
}

#Now we get the nicer table:

mtcars %>% 
  tabyl(gear, cyl) %>% 
  adorn_everything(pct_direction = "col") %>% 
  kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">gear</th>
<th style="text-align: left;">4</th>
<th style="text-align: left;">6</th>
<th style="text-align: left;">8</th>
<th style="text-align: left;">Row Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">9.1% (1)</td>
<td style="text-align: left;">28.6% (2)</td>
<td style="text-align: left;">85.7% (12)</td>
<td style="text-align: left;">46.9% (15)</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">72.7% (8)</td>
<td style="text-align: left;">57.1% (4)</td>
<td style="text-align: left;">0.0% (0)</td>
<td style="text-align: left;">37.5% (12)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">18.2% (2)</td>
<td style="text-align: left;">14.3% (1)</td>
<td style="text-align: left;">14.3% (2)</td>
<td style="text-align: left;">15.6% (5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Column Total</td>
<td style="text-align: left;">34.4% (11)</td>
<td style="text-align: left;">21.9% (7)</td>
<td style="text-align: left;">43.8% (14)</td>
<td style="text-align: left;">100.0% (32)</td>
</tr>
</tbody>
</table>

**Comment by sfirke** [comment]
To clarify one thing, most of the problems in the first example are due to adorning percentages before totals.  If you reverse that order, you get:
```
mtcars %>% 
  tabyl(gear, cyl) %>% 
  adorn_totals("row", name = "Column Total") %>% 
  adorn_totals("col") %>% 
  adorn_percentages("col") %>%
  adorn_pct_formatting() %>%
  adorn_ns()

         gear           4          6           8       Total
            3   9.1%  (1)  28.6% (2)  85.7% (12)  46.9% (15)
            4  72.7%  (8)  57.1% (4)   0.0%  (0)  37.5% (12)
            5  18.2%  (2)  14.3% (1)  14.3%  (2)  15.6%  (5)
 Column Total 100.0% (11) 100.0% (7) 100.0% (14) 100.0% (32)
```

This suffers only from the non-informative 100%s, not the errors.

Thanks for sharing your function, looks like the same totals row/col as doing `denominator = "all"` in `adorn_percentages` and then the rest of the table is like the example here, col-wise percentages.

I think if folks wanted the totals row left as Ns, with no percentages, their best bet would be writing their own function that swaps the original totals row back in after the other adornments.

**Comment by jzadra** [comment]
Ooof.  I way overcomplicated that.

Here's a much simpler (but still hacky) version to accomplish the same thing.

I'm thinking that based on something like this, it would be possible to modify `adorn_percentages()` to check the attributes of the tabyl and see if percentages have already been adorned (I know that isn't in the attributes now, but could be added easily).  And then if the user is trying to adorn the percentages to the same direction, you get a message as such, while if the user is trying to adorn in the other direction, it does something similar to the code below.  Curious to hear other's thoughts about this.

``` r
require(tidyverse)
#> Loading required package: tidyverse
suppressPackageStartupMessages(require(janitor))

adorn_try2 <- function(dat, pct_direction = "col") {
  
  if(!(pct_direction %in% c("row", "col"))) stop("pct_direction must be either \"row\" or \"col\".")
  
  pct_direction_rev <- ifelse(pct_direction == "col", "row", "col") 
  
  dat <- dat %>% 
    adorn_totals("row", name = "Column Total") %>%
    adorn_totals("col") %>%
    adorn_percentages(pct_direction) %>%
    adorn_pct_formatting() %>%
    adorn_ns()
  
  if(pct_direction == "col") {
    dat <- dat %>% 
      rows_update(y = attr(., "core") %>% adorn_totals("row", name = "Column Total") %>%
                    adorn_percentages(pct_direction_rev) %>%
                    adorn_pct_formatting() %>%
                    adorn_ns() %>% 
                    slice(nrow(.)), 
                  by = colnames(.)[1])
  }
  
  if(pct_direction == "row") {
    dat <- dat %>% 
      select(-last_col()) %>% 
      add_column(attr(dat, "core") %>% 
                  adorn_totals("row", name = "Column Total") %>%
                  adorn_totals("col") %>%
                  adorn_percentages(pct_direction_rev) %>%
                  adorn_pct_formatting() %>%
                  adorn_ns() %>% 
                  select(last_col()))
  }
  
  return(dat)
    
}

mtcars %>% 
  tabyl(cyl, gear) %>% 
  adorn_try2(pct_direction = "col")
#>           cyl          3          4         5       Total
#>             4  6.7%  (1) 66.7%  (8) 40.0% (2)  34.4% (11)
#>             6 13.3%  (2) 33.3%  (4) 20.0% (1)  21.9%  (7)
#>             8 80.0% (12)  0.0%  (0) 40.0% (2)  43.8% (14)
#>  Column Total 46.9% (15) 37.5% (12) 15.6% (5) 100.0% (32)

mtcars %>% 
  tabyl(cyl, gear) %>% 
  adorn_try2(pct_direction = "row")
#>           cyl          3          4         5       Total
#>             4  9.1%  (1) 72.7%  (8) 18.2% (2)  34.4% (11)
#>             6 28.6%  (2) 57.1%  (4) 14.3% (1)  21.9%  (7)
#>             8 85.7% (12)  0.0%  (0) 14.3% (2)  43.8% (14)
#>  Column Total 46.9% (15) 37.5% (12) 15.6% (5) 100.0% (32)
```
