### ISSUE TITLE
feature request: signif_half_up()

### ISSUE THREAD

**Issue by khueyama** [sfirke/janitor#314]
I'm currently working on a project that needs halves away from zero rounding and was thankful to come across `janitor::round_half_up()`! Part of this project also requires similar behavior for significant digit rounding, e.g., `signif(12.5, 2)` returns 12 instead of 13. I have an implementation of  `signif_round_up()` working and can put in a PR if it would be of interest to you.

**Comment by billdenney** [comment]
@sfirke should weigh in, but I would think it would fit with the theme of the package.

**Comment by sfirke** [comment]
Sorry to be slow replying! Yeah that sounds in scope. If you have a PR with
tests and documentation that would be appreciated. Let us know if you have
questions or want input. Bill, could you review such a PR?

**Comment by billdenney** [comment]
I'd be happy to review a PR for this.

**Comment by khueyama** [comment]
Great, thanks @sfirke & @billdenney! Have one last push in the office to get through before the holidays but then things will be nice and quiet. Will get things wrapped up and put in the PR sometime next week.

**Comment by sfirke** [comment]
You two are great!  To me, this issue's set of suggestion/pull request/code review/feedback/revision exemplifies the promise of open-source collaborative software.  This is a nice addition to the package and I'm grateful to both of you Kyle and Bill for adding it with such attention to detail in #324.

Happy New Year! :tada:
