### ISSUE TITLE
Adorn both row- and column-percentages in tabyl

### ISSUE THREAD

**Issue by gekess** [sfirke/janitor#319]
Hello and thanks for this delightful package!

Currently, adorn_percentages() only allows for one of the options "row", "col", or "all". In transition tables (think of movers and stayers of classification analysis), it can make sense to read the proportion contained on the base of either, rows or columns, and then compare these findings.

Is there a work-around for this issue or a specific adorn-function I haven't yet found?

Best,
Georg

**Comment by sfirke** [comment]
Hi and thanks!  The problem I see is how to store those multiple values in within each single cell of the tabyl, in an understandable way.  I would probably create 3 tabyls with the different proportions, then compare them?  You could try to hack together a version with them in the same cells if you really want that, by pasting the values together; here's the under-the-hood code for how `adorn_ns()` concatenates % and N in the same cell: https://github.com/sfirke/janitor/blob/master/R/adorn_ns.R#L76

**Comment by gekess** [comment]
Thanks for the input!
