### ISSUE TITLE
Submit to CRAN by Jan 23rd to get ahead of tidyselect

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#325]
I got an automatic notification that changes to the tidyselect package, which will go to CRAN on Jan 23rd, cause a test to fail in janitor.  It appears to be a single test that looks for a specific error message, and I expect tidyselect changed the error message text, causing this to fail.  So, not a serious problem.

But, I think it requires CRAN submission.  And anyway it's been 9 months and we have implemented a bunch of nice updates to the package, so it's probably time to declare version 1.3.0 and send it anyway.

I can handle the CRAN submission process.  Anyone have anything they want to try to ship quickly into v 1.3.0?

**Comment by billdenney** [comment]
If reasonable, I'd like to get #311 in.  I'd like another pair of eyes on it, though.

I don't know if @woodwards may have interest/bandwidth to get #316 in, but that would also be interesting.

**Comment by sfirke** [comment]
Okay I will look at #311!

**Comment by sfirke** [comment]
I want to get #311 in as well as #328 , but the clock is ticking.  I actually think the tidyselect dependency thing will be easier if I just submit a simple patch version to CRAN for now.  So that's my plan: fork the repo back at v 1.2, add a single line commit to fix the failing test under tidyselect, resubmit now, then submit a bigger new version 1.3 of janitor in the coming month or two under less pressure.

**Comment by billdenney** [comment]
That works for me.

**Comment by sfirke** [comment]
Whoa CRAN is fast.  Version 1.2.1 is up now!  https://cran.r-project.org/web/packages/janitor/index.html

**Comment by sfirke** [comment]
This is done, on to the next CRAN submission
