### ISSUE TITLE
Suggestion: allow get_dupes() to use tidyselect

### ISSUE THREAD

**Issue by jzadra** [sfirke/janitor#326]
`get_dupes()` allows you to specifiy columns positively, but you can't negate them (ie `get_dupes(mpg, -cty)` does not work, but `get_dupes(mpg, cty)` does.  

Often there's a single column that serves as an index or key that you know won't have a dupe, so it would be best to remove it rather than specifying all the vars except for it.

**Comment by sfirke** [comment]
This is a no-brainer. Good improvement. Anyone is welcome to claim this
issue and submit a PR!

**Comment by jzadra** [comment]
What the hell. I’ve never done one before and it is high time I learn. I think this is something I can do so I’ll give it a shot.

**Comment by jzadra** [comment]
It's coming along.  First issue I've encountered that requires others input:

When using selection helpers like `starts_with()`, `ends_with()`, `contains()`, etc, there is the possibility that:

1. They catch nothing.  In this case I suggest we through the same error as you used before when there were no columns that matched the variables.
2. Some of the selections match columns, but others don't.  For instance consider that `mtcars %>% select(starts_with("nothere"), mpg)` will just return the mpg column.  Not a problem when you immediately see what you get.  But when expecting to get dupes, it might not be readily apparent that you didn't get anything matching "nothere" given that the return is the full data.frame plus the dupe_count column.  How do we want to handle this?  Should we just add a message indicating which columns were caught by tidyselect, or something else?

**Comment by sfirke** [comment]
First a broad comment, I'm now looking at the code of `get_dupes` and I think you'll want to rewrite even this first bit to be tidyverse handling of `...` instead:
```
uq_names <- as.list(substitute(list(...)))[-1L]
    df_name <- deparse(substitute(dat))
```
Writing functions with tidyverse variable handling is not the easiest thing... but it's really useful to learn :stuck_out_tongue_winking_eye: 

My existing code is a hacky holdover from an earlier version of rlang.  I think on the upside that this stuff is better implemented and better documented now!

Re: your points, let's hold on the error + warning stuff for now.  I expect it might just be okay for say example #2 to use only `mpg` and the user can figure out what happened based on the fact that column 1 is `mpg` and column 2 is `n`.  If `dplyr::select` doesn't throw an error, I don't know that we need to.  We can always layer it in later but that's icing on the cake.

**Comment by jzadra** [comment]
Yep, I already rewrote that first part :).  I've worked with tidyverse and rlang before.  I'm just new to doing PRs and the method for contributing to someone else's package.

In that case, I think it's about ready for someone else to look at.  What's my next step?

**Comment by sfirke** [comment]
Nice!

**PR:** If you have forked & cloned the repository and made a branch, then GitHub should have a button from your branch to create a pull request into the master branch of sfirke/janitor.  There are some screenshots here: https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR

**Tests:** You can take a stab at creating test(s), adding them here: https://github.com/sfirke/janitor/blob/master/tests/testthat/test-get-dupes.R  For instance:

- mtcars %>% get_dupes(contains("cy"), mpg) should be identical to mtcars %>% get_dupes(cyl, mpg)

Is there anything else tidyselect-specific to add?

**Docs**: And I'm trying to think what updates to documentation.  Maybe note in the parameter definition for `...` that tidyselect helpers can be used?  Then add an example showing that `library(dplyr)` followed by `mtcars %>% get_dupes(starts_with("d"))` works?

After updating documentation run `devtools::document()`.

**Comment by jzadra** [comment]
Thanks.  Should I do the PR first and get feedback, or do the tests and docs before the PR?

**Comment by sfirke** [comment]
Might as well do the tests and docs first, then all the review can go at
once.

**Comment by jzadra** [comment]
Sounds good.  One other thing while I'm in here: should we allow the user to specify the name of what is currently the "dupe_count" column (leaving that as the default)?

**Comment by jzadra** [comment]
Looks like I was supposed to fork before cloning, and I can't push now to create the pull request?  I just cloned and then make a new branch in RStudio.

**Comment by sfirke** [comment]
Whoops yep I think you have to fork first.  You could copy your altered files into a different folder, delete your clone of the repo, fork + clone from sfirke/janitor, and re-insert your altered files.  You'd lose your commit history since it would now look like one big commit, but I think that's fine in practice.  This is still the size of something that would be one commit, and we'll squash to one commit it anyway before merging.

**Comment by jzadra** [comment]
I'd be grateful for any feedback about both the changes and how I did the PR!

**Comment by sfirke** [comment]
This was great, thanks @jzadra !  I know it took a little while but it feels good to have this merged in, I appreciate the idea & execution.
