### ISSUE TITLE
let crosstab be called in a pipeline

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#33]
- [x] Update `crosstab()` code
- [x] Update vignette

Idea from @chrishaid

by creating another function.  Here is a crude mockup:
```
crosstab_df <- function(dat, ...){
  names <- as.list(substitute(list(...)))[-1L]
  names <- unlist(lapply(names, deparse))
  trimmed <- dat %>% select_(.dots = names)
  crosstab(trimmed[[1]], trimmed[[2]])
}
```

Which works: `mtcars %>% crosstab_df(cyl, am)` (sort of, variable name is lost in the result)

Do this for `tabyl()` too as `tabyl_df()`, right now it's tedious to have a dplyr pipeline with a filter, etc. that I have to interrupt to use tabyl() (or use `use_series()` which isn't even an option for `crosstab()`).

**Comment by chrishaid** [comment]
I'm working on this now, which means I'm muddeling through a lot of NSE problems.

**Comment by sfirke** [comment]
Awesome!  And not awesome, respectively.  I have had a lot of trouble with NSE while writing this package :-1:

When I got your email about using S3 to have a method work on different classes, I thought "I'm going to learn something here."  I googled it, and I think I get what you're going for, which would be brilliant.

**Comment by chrishaid** [comment]
I've got it mostly working.  Can you make me a contributor on this repo so I can push a branch?

**Comment by chrishaid** [comment]
Actually, igonre that last request.  I've just forked and recloned the repo.

**Comment by sfirke** [comment]
Very nice work.  I am leaving this open just until I update the vignette accordingly.  And I'll try to adapt the approach you've taken here to the `tabyl()` function which I also often call from a pipeline.
