### ISSUE TITLE
adorn_ns() decimal format

### ISSUE THREAD

**Issue by IvanWilli** [sfirke/janitor#330]
Thanks for this excellent package. 
Is there any way to change the decimal character from "." to ",". When I want to do it by kable is too late, and it can´t be done.
Thanks,
Best

**Comment by sfirke** [comment]
Hi! Could you post a code example, showing what happens and what the
desired result is ? That would help me figure out the precise
issue/request.

**Comment by IvanWilli** [comment]
Yes, sorry. 
Reformulating the problem (title edited), I think it´s the adorn_ns() function the thing. Otherwise, it works fine. I mean, display the decimal.mark change.

library(janitor)
library(kableExtra)
# without adorn_ns()
mtcars %>% tabyl(cyl, gear) %>% adorn_percentages() %>% 
            kable(format.args = list(decimal.mark = ',', big.mark = "."))
# wit adorn_ns
mtcars %>% tabyl(cyl, gear) %>% adorn_percentages() %>% adorn_ns() %>% 
            kable(format.args = list(decimal.mark = ',', big.mark = "."))

Thanks!

**Comment by sfirke** [comment]
Mm I see, thanks.  If you in general want decimal points to be commas, could this be solved by globally setting your options?  E.g., from https://stackoverflow.com/a/27158388/4470365 I got `options(OutDec= ",")`.  And that changes it for me:
```

cyl | 3 | 4 | 5
-- | -- | -- | --
4 | 0,0909090909090909 (1) | 0,727272727272727 (8) | 0,181818181818182 (2)
6 | 0,285714285714286 (2) | 0,571428571428571 (4) | 0,142857142857143 (1)
8 | 0,857142857142857 (12) | 0 (0) | 0,142857142857143 (2)
```
If you don't want to change your global options and do this one data.frame at a time, you could do it like this:
```

result <- mtcars %>%
  tabyl(cyl, gear) %>%
  adorn_percentages()

result %>%
  format(decimal.mark=",") %>%
  adorn_ns(ns = attr(result, "core")) %>%
  kable()
```

**Comment by IvanWilli** [comment]
Solved. Second options is great.
Thanks man!

**Comment by sfirke** [comment]
For future readers: further discussion at https://github.com/sfirke/janitor/issues/378.
