### ISSUE TITLE
`make_clean_names()` Drops Unicode First Characters

### ISSUE THREAD

**Issue by billdenney** [sfirke/janitor#331]
As the title suggests, `make_clean_names()` drops Unicode first characters.

```r
library(janitor)
make_clean_names(c("not_first_µg_dna", "µg_dna"))
# [1] "not_first_µg_dna" "g_dna"      
```

**Comment by sfirke** [comment]
Weird.  Any idea what causes it or how to fix it?

**Comment by billdenney** [comment]
I just had a chance to look at it, and apparently, it is caught by the `[[:punct:]]` part here: https://github.com/sfirke/janitor/blob/5605e35d30f05097055ac13f41796dbcd21a86a5/R/make_clean_names.R#L57

I just found a rabbit hole that we may need to stuff full of dynamite.

My first find was that "[:punct:]" is defined as a small list of punctuation characters (https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/regex).  But, I noticed that these named characters are locale-specific.  So, I read the locale page, and found that I should try a different locale here to see if that was part of the issue-- and it is.

So, replacing the line linked above with the following expansion of "[:punct:]" seemed to work for me, but it then makes the regexp much less readable and may fail for other definitions of "[:punct:]":

```
    gsub("^[[:space:]!\"#$%&'()*+,-./:;<=>\\?@^_`{|}~\\[\\]]+", "", .) %>% # remove leading spaces & punctuation, using the default [:punct:] is locale-specific, so punctuation is expanded to all expected punctuation characters.
```

Would you like that as a PR?

**Comment by sfirke** [comment]
Interesting!  I can't reproduce the original problem:
```
> make_clean_names(c("not_first_µg_dna", "µg_dna"))
[1] "not_first_µg_dna" "µg_dna"
```
Is that due to my locale, and for me `[:punct:]` does not include the `µ` symbol but for the locale you used for the initial example, it does?

**Comment by sfirke** [comment]
Also, this got me thinking about solving it via transliteration, and I went back to https://github.com/sfirke/janitor/issues/204#issuecomment-443318211.  Do you think that simple swap in of `iconv` that you suggest there still makes sense?

**Comment by billdenney** [comment]
Yeah, I would guess that the fact you're not seeing the issue is a locale difference.  I'm running RStudio on Windows 10 with a US English locale (the actual name is somewhat different).

The change in issue 204 would break backward compatibility, but in my opinion, that's worthwhile.  I will add in a warning if there is a change with transliteration for how they can get the old behavior.

I'll make a PR for that.

**Comment by sfirke** [comment]
Ah indeed, the initial mu drops for me on Windows 10, not on Ubuntu 18.04.  Which to me makes this a worse bug because it breaks reproducibility across my two laptops in the same room!  A PR for #204 would be great, and I agree the breakage is worthwhile.

I'm not sure if that is breaking _enough_ to call this next release janitor 2.0.0 - I think so, at least https://semver.org/ says "any backwards incompatible changes" should bump the major version.  Now that said dplyr makes bigger breaking changes than this without going to 1.0.0, but maybe they could say because they've never hit 1.0.0 they are still in progress and can break things.

If we implement the fix in #204, it fixes this particular example.  Do you think there would be other instances of this phenomenon not caught by the `iconv` fix?

**Comment by billdenney** [comment]
I've worked on it for about 1-2 hours at this point, and I'm coming to the following thoughts:

1. It seems likely impossible to maintain all previous behavior and fix this.
2. The fixes that I'm finding will wipe out all Unicode for the current method of use.
3. We want the new solution to work in a cross-platform, locale-independent way.
4. It is probably time to rethink how `make_clean_names()` works.

I'd propose that we change the way that `make_clean_names()` works with the following goals:

1. There is one option that will simplify everything down to a simple, ASCII-only representation.  That will be the default.
2. The current replacement for "%" and "#" will be generalized to any replacements (defaulting to those two).
3. If you do not convert to ASCII-only, try to make the new name match the old behavior as much as possible, but don't require the old behavior to work as it did.
4. Allow Unicode and other characters in if ASCII-only is not selected.
5. In all scenarios where ASCII-only is not selected, the output names may be slightly less usable (in other words, they may require using back-ticks), but that is a selection that the user is making when not selecting ASCII-only.
    1. We could evaluate these scenarios in the future, but hopefully, the above would be more robust, platform-independent, and future-proof.

`iconv` is locale-dependent, and so I think that it should be avoided.  Building on @Tazinho's suggestion in https://github.com/sfirke/janitor/issues/204#issuecomment-393681608, I think that we would move to the following instead of the `iconv` fix mentioned in #204: 
`stringi::stri_trans_general(testing_vector, id=c("Greek-Latin;Latin-ASCII;Accents-Any;Any-ASCII"))`

In this, I would incorporate relevant aspects of #254, #303, #316, and #338.

What do you think?

As for version 2.0 or not, I would lean toward it being version 2.0 since I think `clean_names()` is one of the features that a lot of people use (based on GitHub issues reported for it).

**Comment by billdenney** [comment]
@sfirke, Can we drop the `make.names()` part or make it optional?  It is locale-specific, and it converts Japanese characters to something not Japanese on my system:

```r
make.names("Ã¢âぁÂ¬")
# [1] "Ã.â.U.3041.Â."
```

**Comment by sfirke** [comment]
Yep your specific comment re: make.nams sounds good and I'm on board with the massive rewrite!
