### ISSUE TITLE
By March 14th: Fix bugs caused by tibble 3.0.0

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#333]
Got an automated email alerting me that janitor tests are failing as a result of breaking changes to what will be tibble 3.0.0, currently on GitHub and heading to CRAN around March 14th.  Gonna be a busy month but I suppose I'm fitting this in.

**Comment by sfirke** [comment]
Is it time to rush out janitor 1.4.0??  Making this change in two places - the older CRAN fork and the dev master branch - is tiresome.

**Comment by sfirke** [comment]
In progress on this branch: https://github.com/sfirke/janitor/tree/tibble300-333

**Comment by sfirke** [comment]
Oh, and CRAN has also requested changes because in R 4.0.0 the default will be `stringsAsFactors = FALSE` which is great but apparently breaks some janitor tests.  That should just be a matter of explicitly saying `stringsAsFactors = TRUE` when I mean that.

**Comment by billdenney** [comment]
For the R 4.0 stringsAsFactors updates, if any (accidental) factor conversion occurs within `janitor`, I think that we should move toward a no-factors-conversion stance (like both R base and tidyverse).

**Comment by sfirke** [comment]
You mean, if it comes in as a factor it goes out as a factor, and same with
not-a-factor, goes out not-a-factor?

**Comment by billdenney** [comment]
Yep, that's what I mean.  :)
