### ISSUE TITLE
Submit janitor 2.0.0 to CRAN on April 7th

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#335]
I've closed #333 but the fix must go to CRAN by March 14th.  There are enough changes on this dev version that it will be janitor 1.3.0.  Let's see what else we can get shipped.

- [x] Sam will review and merge #311
- [x] Close #195 adorn_ns and character columns 
- [ ] ...

**Comment by sfirke** [comment]
Changed due date after receiving my final :skull: reminder from CRAN.  Need to address #348 

I could do another bugfix submission pretty quickly, to address #348 dplyr stuff and the trivial CRAN fix that's already been made in this commit: https://github.com/sfirke/janitor/commit/5f0a4c8617988ee0bcbf37f414a4552d422b37a4

That would take off the time pressure for janitor 2.0.0 which as long as we're still adding stuff, could be good.  But maybe it helps to have the fire under me.

Maybe if life gets too hectic b/c of coronavirus or something else, the bugfix route is the way to go.

**Comment by sfirke** [comment]
Well life has gotten too hectic b/c of coronavirus, I'm watching the kids this week and have very little time.  That said I lean toward, submitting a mostly-done 2.0.0 to CRAN honors the work that's been done, and we can always add more stuff later -- rather than keeping 2.0.0 on the shelf in hopes that it'll be finished soon.  So planning to find the time I can to do what I can and stay on track, timeline-wise.

**Comment by sfirke** [comment]
Update :warning: I don't have the time to even put together a mostly-done 2.0.0 by the end of this weekend.  With release notes, vignette update, revdep checks (!) etc.  Now I'm just planning to branch the current CRAN version and cherrypick the fixes needed for R 4.0.0, tibble 3.0.0, dplyr 1.0.0.  Even dplyr can wait a little longer, it's going to CRAN May 1 so I'd need to be ahead of that. :running_man:

**Comment by billdenney** [comment]
With how life is going here, I understand not having the time.  I hope that everyone there is well, and good luck!

**Comment by sfirke** [comment]
Thanks Bill!  We are pretty good right now all things considered.

I started in on a "simple" bugfix branch but it's a mess b/c the changes for compatibility for tibble, dplyr, base R are all also addressing breaking changes to janitor 2.0.0.  Too confusing.  New plan is to get some sleep then see how fast I can ship a 2.0.0 tomorrow 🤞 .  Hope you and your family are well!

**Comment by sfirke** [comment]
Got a huge amount done today, but not ready to ship - and I'm looking at the next six days of being with the kiddos all day.  I'll see what I can move along at nap and at night and I guess I'll see if the package is removed from CRAN as is stated may be a consequence for my delayed timeline...

**Comment by billdenney** [comment]
It may be worth an email to CRAN to let them know that you're working on it but delayed due to COVID.  They can be forgiving, but they need a quick message to know that you're working on it.  (I once had a bit of grace time with a delay for PKNCA.)

**Comment by sfirke** [comment]
Good call, I've dropped them a line.

**Comment by sfirke** [comment]
Just about ready to go!  So annoying that _today_ is the day that Mac OS builds on Travis CI are failing for a seemingly-unrelated reason.  Bonus points if anyone can pull the version currently on GitHub and run `devtools::check()` locally on their Mac.

**Comment by billdenney** [comment]
Hooray!  Great work getting this over the line!
