### ISSUE TITLE
Set up auto-build pkgdown site with every commit to master

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#337]
I fall behind on this because I forget to build the site manually.  I should be able to automate it, anyone have a suggestion for a package or how-to to get this set up easily?

**Comment by sfirke** [comment]
This was brutal.  I struggled with Travis, made worse because I started with it long enough ago to be a legacy repo, and never got it working.  Then got GitHub Actions working and struggled to undo the Travis mess.  But I think this works - http://sfirke.github.io/janitor/ rebuilds when a commit is pushed to master.  Whew!

**Comment by billdenney** [comment]
Great work, thanks!
