### ISSUE TITLE
Deprecate functions appropriately for v 2.0.0

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#346]
Deprecate stop these functions:

- crosstab
- adorn_crosstab
- use_first_valid_of
- convert_to_NA

Follow https://cran.r-project.org/web/packages/lifecycle/vignettes/lifecycle.html

And update janitor_deprecated.R appropriately.

**Comment by billdenney** [comment]
`remove_empty_rows()` and `remove_empty_cols()`?

**Comment by sfirke** [comment]
I don't get why the merging of the PR didn't auto-close this -- but at any rate, these are gone!
