### ISSUE TITLE
Error msg  with basic example of tabyl and adorn_totals 

### ISSUE THREAD

**Issue by sfd99** [sfirke/janitor#360]
_Love_ the janitor pkg. (ver 1.2.1)

**Just running this in Rstudio (or just in plain R), 
works great:**
> mtcars %>%
    tabyl(am, cyl)
 am 4  6  8
  0    3 4 12
  1    8 3  2

**but, when i run:  (from the vignette example...)**
mtcars %>%
  tabyl(am, cyl) %>%
  adorn_totals()

**I'm getting _this_ error:  
 (this used to work _just fine_ in the past...)**

Error: Assigned data `name` must be compatible with existing data.
ℹ Error occurred for column `am`.
x No common type for `value` <character> and `x` <double>.

**Here are my loaded pkgs:**
> (.packages())  [1] "magrittr"  "reshape2"  "tidyr"      [4] "ggplot2"   "dplyr"     "janitor"    [7] "stats"     "graphics"  "grDevices" [10] "utils"     "datasets"  "methods"   [13] "base"
--

_Help! anyone?_
**SFd99
San Francisco
UBUNTU LINUX 18.04, latest versions of Rstudio and R.**

**Comment by sfirke** [comment]
Can you run devtools::session_info() and paste the results of which
packages you're running?

**Comment by sfd99** [comment]
Ok Sam,
installed janitor 1.2.1.9000
and now it WORKS! 

mtcars %>%
    tabyl(am, cyl) %>%
    adorn_totals()

    am  4 6  8
     0  3 4 12
     1  8 3  2
 Total 11 7 14

I was going crazy...THANKS!
Yeah, the famous adventure
of "other" changing pkgs...
they may break depending pkgs.

thanks again!!!

**Comment by sfirke** [comment]
Excellent! This was useful to hear, thanks. They (other maintainers) gave
me decent notice to update, I just need to call v2 of janitor done and send
it in!

**Comment by sfd99** [comment]
_GREAT!_

**_btw:_**
to get Total sum for BOTH rows AND cols:

mtcars %>%
    tabyl(am, cyl) %>%
    adorn_totals(c("row", "col"))
    am  4 6  8 Total
     0  3 4 12    19
     1  8 3  2    13
 Total 11 7 14    32

So, SUGGESTION: 
_also_ allow keyword:
**"both"** 
as param to: 
   adorn_totals("both")

faster coding... :-)

**Comment by sfirke** [comment]
Sure, I could see that, though for the next release - right now I'm racing to get 2.0.0 to CRAN to get errors like yours fixed.  I'll close this one since we understand the behavior, could you open a new issue with your suggestion in your last comment?  Thanks!
