### ISSUE TITLE
very wide table as html output in three-way table

### ISSUE THREAD

**Issue by CITESmike2018** [sfirke/janitor#375]
In rmarkdown a very wide  three-way table is produced.

**Comment by sfirke** [comment]
Could you share an example where I can reproduce the behavior?

**Comment by CITESmike2018** [comment]
Hi,

Thanks for the prompt response.

I think I have figured it out. The wide table appears when using the  kable
package. And it works well with  pander.

Also thanks  for tabyl.

See attached code.
