### ISSUE TITLE
Improve tabyl error message when incorrectly called like tabyl(mtcars$cyl, mtcars$gear)

### ISSUE THREAD

**Issue by JeffreyLusk** [sfirke/janitor#377]
EDITED WITH SOLUTION:  I re-parsed the Var_2 as Character, but it still wouldn't work.  A few more attempts and I figured out it didn't like the way I was calling the function using the "data.frame$variable" format for each variable (highlighted in error message below), so I followed the piped format in the vignette: new_1<-"data.frame"%>%tabyl(Var_1,Var_2)... and now it works properly. 

ORIGINAL MESSAGE: This is more of a question than a bug or issue, so hopefully a reproducible example won't be needed.  

Description: I have a survey data set and wish to create a two-way contingency table.  Var_1 is a Yes/No response parsed as "Character", Var_2 is a group ID code parsed as "Factor".  I called the tabyl function as: 

tabyl(Var_2,Var_1, show_na=FALSE) 

and got the following error (with my actual variable names):

Error in is.factor(dat) && show_missing_levels : invalid 'y' type in 'x && y'
5. tabyl.default(lgco.data$CodeID, lgco.data$Q3, show_na = FALSE)
4. tabyl(lgco.data$CodeID, lgco.data$Q3, show_na = FALSE)
3. eval(lhs, parent, parent)
2. eval(lhs, parent, parent)
1. **_tabyl(lgco.data$CodeID, lgco.data$Q3_**, show_na = FALSE) %>% adorn_pct_formatting(digit = 1)

I reversed Var_1 and Var_2, in the call, but only got a 1-way contingency table for Yes/No counts.  So it appears my data were parsed incorrectly.  What data type should each variable be for this analysis?

**Comment by sfirke** [comment]
Sorry for the delayed response.  I'm glad you figured it out.  Yes, calling tabyl like `tabyl(mtcars$cyl, mtcars$gear)` is not valid -- but the result is not helpful.  You got an unclear error, and the example I gave runs "successfully"!

I think I will add functionality that checks if the value passed to the `show_na` argument is not a simple `TRUE` or `FALSE` and if so, prints a message saying that and also explaining, if you meant to create a two-way tabyl, they must be columns in the same data.frame and called with bare names, not the `$`.  (I'll have to work on that text).
