### ISSUE TITLE
Feature Request: play nicely with flextable to produce pretty output

### ISSUE THREAD

**Issue by higgi13425** [sfirke/janitor#382]
## Feature requests

add a    _to_flextable()_   function,
much as the {gtsummary} package uses as_flextable()
to make output a flextable, and 
thereby accessing the many formatting functions in the {flextable} package

## Ideal future state

Borrow code from gtsummary::as_flextable()

create _to_flextable()_ function

take fabulous tabyl output,
and easily be able to use all the formatting fun in {flextable},
which plays well with HTML, PDF, and MS Word.

**Comment by sfirke** [comment]
I have never used `flextable` - I am behind the times - so wouldn't know how to proceed here.  If someone can contribute code and examples, we can reopen it.  I'm not passing judgment on the idea either way, I just can't implement it myself.
