### ISSUE TITLE
Feature request: adorn_mean, adorn_median

### ISSUE THREAD

**Issue by francisbarton** [sfirke/janitor#383]
As well as `adorn_totals`, it would be great if `janitor` had an option to adorn a mean or median to the end of specified rows or columns.

**Comment by sfirke** [comment]
Sorry I never responded to this 😔  At this point I'm going to close this as unplanned.  `tabyl` will stay minimal for quick distributions, I am hopeful another package provides a more thorough implementation of a grammar of tables.
