### ISSUE TITLE
Ordered factors and 3-way tables in Janitor

### ISSUE THREAD

**Issue by HenkvdKolk** [sfirke/janitor#386]
With a dataframe with three *ordered factors*, Janitor does not produce a 2x2x2 table. With unordered factors there seems to be no problem. Why is that? The example is with numbers because of the rbinom I used, but the output is the same. Is seems that the ordered nature of x is the biggest problem, with a simple factor I get what I need. This is problematic with low/middle/high type of factors.

```r
library(tidyverse)
library(janitor)

n <- 100
data <- rbinom(n, 1, 0.5)  %>% factor(order = TRUE, levels = c("0", "1")) %>% as_tibble() %>% rename(., x = value)
data$y <- rbinom(n, 1, 0.5) %>% factor(order = TRUE, levels = c("0", "1"))
data$t <- rbinom(n, 1, 0.5) %>% factor(order = TRUE, levels = c("0", "1"))

data %>% 
  tabyl(x, y, t, show_na = FALSE) %>% 
  adorn_totals("col") %>% 
  adorn_totals("row") %>% 
  adorn_percentages("col") %>% 
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns() #show the numbers of cases
```

**Comment by sfirke** [comment]
Thank you for this bug report!  I apologize for not realizing what you were saying, that this command errors (I didn't run the code).  I will aim to get this fixed in the next week or so.

**Comment by HenkvdKolk** [comment]
Thanks. I will frame this e-mail as this was my first successful bug-report. I like the package (the tabyl part at least), so also thanks for creating it.

**Comment by sfirke** [comment]
Fixed :grin:  Thanks again for this bug report!
