### ISSUE TITLE
have tabyl() take multiple variables and compare them?

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#39]
This might be better off as a separate function.  The idea would be that `mtcars %>% tabyl(cyl, gear)` returns the result of:

```
full_join(tabyl(mtcars$cyl), tabyl(mtcars$gear), by = c("mtcars_cyl" = "mtcars_gear")) %>%
  setNames(c("value", "cyl_n", "cyl_percent", "gear_n", "gear_percent"))

# A tibble: 5 x 5
  value cyl_n cyl_percent gear_n gear_percent
  <dbl> <int>       <dbl>  <int>        <dbl>
1     4    11     0.34375     12      0.37500
2     6     7     0.21875     NA           NA
3     8    14     0.43750     NA           NA
4     3    NA          NA     15      0.46875
5     5    NA          NA      5      0.15625
```

Would it return n?  %?  Both?  Have that be user-specified?  If just n, it could take advantage of the `adorn_crosstab` function I'm working on.

**Comment by sfirke** [comment]
@ffirke is this what you were talking about?

**Comment by ffirke** [comment]
No, but it's interesting.

I just meant tabyl taking two results and effectively grouping by both of them. So I can run transactions %>% tabyl(year, team) and get a dataframe with the number of results for each team/year combination (with optional percentages by group--there were 10 White Sox transactions in 2015, which is 1% of total transactions in the DF, 10% of the 2015 transactions, and 25% of the White Sox transactions).

All this behavior is basically just similar to SAS's proc freq.

**Comment by sfirke** [comment]
I think `crosstab()` - soon to be a 2-way `tabyl()` - does this.
