### ISSUE TITLE
Three-way tabyl and chisq.test

### ISSUE THREAD

**Issue by korailR** [sfirke/janitor#392]
The chisq.test function doesn't work for a three-way tabyl.

**Comment by sfirke** [comment]
A three-way tabyl is a list.  You can run any function on the list with `purrr::map`, here's an example:
```
mtcars %>%
  dplyr::mutate(gear = ifelse(gear == 3, 5, gear)) %>%
  janitor::tabyl(cyl, gear, am) %>%
  purrr::map(chisq.test)
```

This use case seems infrequent to me.  If there was sufficient demand, I could adapt `janitor::chisq.test` to auto-map when called on a list of tabyls, which is how all of the `adorn_` functions work.  But right now with limited time that does not feel like a priority to me, when people can just call `purrr::map`.
