### ISSUE TITLE
A crosstabyl function

### ISSUE THREAD

**Issue by korailR** [sfirke/janitor#393]
I like tabyl very much, but to produce a crosstab with percentages and totals, I have to write many lines of code. When teaching R to beginners or doing cross-tabulations, you want powerful, flexible and easy-to-use functions. Ideally, one function should be available to produce a crosstab with several arguments to display row or column percentages, N row or colum totals, digits, etc..

Something like that:

humans %>%
  crosstabyl(gender, eye_color, percent = "row", digits = 1, total = T, n = T)

**Comment by sfirke** [comment]
Thank you.  Funny enough, that was how the original `crosstab` and `adorn_crosstab` functions worked.  They were all in one.  I split them up to be modular, which is more in line with the tidyverse approach.  It gives the user finer control.  There are so many tuning arguments in the different `adorn_` functions that a single monster function would have a dozen or so arguments.  Though I agree that a downside is having to repeat many lines of code.

If you keep repeating the same set, you could bundle them into a single function.  Or someone could write a single master function to pass arguments through to all the `adorn_` functions, like what you lay out.  It wouldn't be too hard to program.  But the janitor package will stick with the modular approach.
