### ISSUE TITLE
round_half_up() fails to round up for certain decimals (precision issue)

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#396]
From the StackOverflow post where I found this function, [someone pointed out a bug ](https://stackoverflow.com/questions/12688717/round-up-from-5#comment110611119_12688836)in June:

> There are numerical precision issues, e.g., `round2(2436.845, 2)` returns `2436.84`. Changing `z + 0.5` to `z + 0.5 + sqrt(.Machine$double.eps)` seems to work for me

Indeed, `round_half_up(2436.845, 2)` yields `2436.84`.  This function should probably have the same fix implemented, along with a test.

**Comment by JJSteph** [comment]
Removing the trunc() formula from the round_half_up() formula seems to work. round_half_up(2436.845, 2) yields 2436.85. What kind of testing would you like to see?
