### ISSUE TITLE
crosstab() takes lists and weird things happen

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#40]
Can we somehow disable feeding lists as arguments to crosstabs?  Not a huge deal in practice, as it's not an intended use, but I'd rather it error than produce a nonsensical result.  Look into it.

**Comment by chrishaid** [comment]
Probably.  The reason it takes lists right now is to deal the the non-standard evaluation in the basic `crosstab()` function when passing it columns from a data.frame (which is done by the `crosstab.data.frame()` method.

My guess right not is that that we should do what Hadley does:  there should be a `crosstab_()` method that uses standard evaluation and which is ultimately what get's called by any other `crosstab`-like function: one with NSE,  the pipeline-able version, etc.

**Comment by chrishaid** [comment]
Also: what kind of weird things are you seeing?

**Comment by sfirke** [comment]
For instance:
```
L <- list("a", "a", 1, 2)
x <- c(1, 1, 2, 2)
crosstab(L, x)

# A tibble: 2 x 5
      L vec1.1 vec1.2  vec2     a
* <chr>  <dbl>  <dbl> <dbl> <dbl>
1     a      1      2     1     2
2     a      1      2     2     2
```

Is nonsensical.  I'd expect a 3x2 result, with 1, 2, a on the row names and 1, 2 on the columns.

**Comment by sfirke** [comment]
@chrishaid : I'm getting close to CRAN submission (!) and was about to close this issue, as it's not practically a problem and right now we need `crosstab()` to accept lists, as you note.  But wanted to come back to your comment about a `crosstab_()` function, Hadley-style:

1. Do you think this package should take that approach?
2. If we don't do it before submitting to CRAN, and then change it later, any sense of whether that would be backward compatible?

Trying to balance getting this on CRAN, since it works, vs. getting it right.

**Comment by sfirke** [comment]
Bah, not worth sweating: let people coerce their lists into vectors themselves.  I think eventually you'll only be able to crosstab 2 columns in the same data.frame anyway.
