### ISSUE TITLE
Julia version of janitor?

### ISSUE THREAD

**Issue by lindblb** [sfirke/janitor#401]
Love your package sir, as a fellow data scientist it is invaluable. 

I'm wondering, how would you feel about someone making a Julia version of Janitor? That way, there would be an R, Python and Julia version of the package?

It doesn't have to be called 'Janitor' per se, if you desire. Let me know!
@sfirke

**Comment by sfirke** [comment]
Thanks for the kind words!  I'd be happy if someone made a Julia version of janitor, like [pyjanitor](https://github.com/ericmjl/pyjanitor) -- and actually, it looks like pyjanitor has taken on quite a life of its own.  I can offer moral support and maybe a little advice, though don't know any Julia so can't help beyond that.  Anyone who is so inclined can go for it!

**Comment by lindblb** [comment]
Thank you sir! Follow the progress at [https://github.com/bradlindblad/Janitor.jl](https://github.com/bradlindblad/Janitor.jl)
