### ISSUE TITLE
Resolve CI provider situation

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#409]
I haven't looked into the details but Travis changed ownership and is making plans more restrictive.  Could be a good time to switch to GitHub CI.  Or move the project to Gitlab or elsewhere but realistically I don't have the bandwidth for that.

https://ropensci.org/technotes/2020/11/19/moving-away-travis/

**Comment by bryceroney** [comment]
I've had some success adding Github actions to my, albeit small, packages. Happy to take a look at this.

**Comment by billdenney** [comment]
I just created a PR for this (I didn't see your comment before starting it, @bryceroney, sorry!).  If the GitHub action checks work, then the PR makes the switch.

**Comment by sfirke** [comment]
Thanks @bryceroney for the offer :+1:   And Bill for implementing!

**Comment by bryceroney** [comment]
@billdenney  Not a problem, I spent a bit of time on Saturday trying to make it work and then realised I had a typo just as you'd submitted this. Either way it got done!
