### ISSUE TITLE
Submit version 2.1 to CRAN

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#411]
I just helped someone debug `janitor::round_half_up` and the problem was them not having the dev version, on CRAN #396 is not patched so `round_half_up(.575, 2)` gives you the incorrect result `0.57`.  This is bad enough it should go to CRAN soon.

I can do that in the next week or two - maybe over Thanksgiving?  We just have bug fixes right now so shouldn't affect any packages that rely on janitor.  If anyone has something they want patched or addressed before it goes to CRAN, now's the time to mention it.

**Comment by billdenney** [comment]
I don't have anything outstanding.

**Comment by sfirke** [comment]
I finally polished everything for submission, then just received this error when I submitted:
```
Error: Submission failed:
The submission team is on vacation from Dec 18, 2020 to Jan 4, 2021
During this time the submission of packages is not possible.
Sorry for any inconvenience.
```
Too bad that I can't close this task, but vacation is good too.  I'll plan to freeze the Github version of this package until I submit on Jan 4th.

**Comment by sfirke** [comment]
Submitted this morning! 🎉  When (if?) it's accepted, I'll tag the release on GitHub and flip to version 2.1.0.9999.

**Comment by billdenney** [comment]
Hooray!
