### ISSUE TITLE
Janitor f/GIT:  Vignette Help Pages yield error for any command help

### ISSUE THREAD

**Issue by sfd99** [sfirke/janitor#412]
**_Hi Sam,_**

Looking forward to the **adorn_totals()**
with the new  **"both"** option.

So, I d/l the latest janitor version:  
  2.0.1.9000 
via: 
  devtools::install_github("sfirke/janitor")

hoping to find the new "both" adorn feature.

Janitor installed OK,
_but_ clicking the 
**Vignette Help Pages**
for  _any_ Janitor command,  ie adorn_totals(),
returns:
_Error in fetch(key) : lazy-load database '/home/ray/R/x86_64-pc-linux-gnu-library/4.0/janitor/help/janitor.rdb' is corrupt_

**SFd99
R version 4.0.3      (latest)
Rstudio 1.3.1073   (latest)
Ubuntu Linux 20.04  (latest)**

**Comment by sfirke** [comment]
When you install a package that you're using and get that "lazy-load
database .. is corrupt" message, try restarting R and see if it goes away.

**Comment by sfd99** [comment]
ok! will try restarting R 
right now, Sam!

**Comment by sfd99** [comment]
Ok! restarted R.
‘janitor’ version 2.0.1.9000 Help Pages now OK! 
Thanks, Sam...

**quick Q:**
In which J version 
will the  adorn_totals() "both" option be available?.

**Comment by sfirke** [comment]
if you just installed the latest janitor version, it should have "both" - give it a shot?

```
mtcars %>%
  tabyl(am, cyl) %>%
  adorn_totals("both")
    am  4 6  8 Total
     0  3 4 12    19
     1  8 3  2    13
 Total 11 7 14    32
```

**Comment by sfirke** [comment]
And I hope to get version 2.2.0 released on CRAN in the next month, it would have this functionality.

**Comment by sfd99** [comment]
_Yay!_ 
new "both" option
works **GREAT** in V 2.01.9000

stay safe, Sam!
**sfd99**
