### ISSUE TITLE
Excel dates before the era begins do not exist (but they do with excel_date_to_numeric())

### ISSUE THREAD

**Issue by billdenney** [sfirke/janitor#423]
## Feature requests

It is unclear the best way to handle negative dates in `excel_date_to_numeric()` as they are undefined in Excel.

## Bug reports

In Excel, the formula `=DATE(1899, 12, 31)` shows a date of 1 March 3700.  Overall, it appears impossible to represent dates as dates before the year 1900 in Excel.

The below is not accurate in Excel, but it is rational based on continuing the number line to be negative.  My first thought is to just leave it as is, and my second thought is to issue a warning.

```r
excel_numeric_to_date(-1:0)
# [1] "1899-12-30" "1899-12-31"
```

Thoughts?

Related to #422

**Comment by sfirke** [comment]
Yes, I agree with you - good to have it just continue the number line, and printing a warning would be appropriate too.  It could be a once-per-session or per X-hours warning like you've implemented elsewhere.  Kinda funny about Excel not bothering with dates before 1900 😂

**Comment by billdenney** [comment]
When you've had a chance to look at #422, I'll add this in.  #422 is more important than this-- Especially because if the date is actually coming from Excel, this isn't possible.

**Comment by billdenney** [comment]
(Not so) Fun fact:  The date January 0, 1900 also can be created in Excel by taking January 1, 1900 and subtracting 1 from it.  I'm walking away from that one.
