### ISSUE TITLE
tabyl() and crosstab() should return data.frame

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#44]
So that all rows are visible when it prints to console..  As much as I love tibbles, for exploratory commands like this it's annoying not  to see the bottom of the list.

**Comment by chrishaid** [comment]
I agree.

*Chris Haid*

Director of Research and Analysis

KIPP Chicago

312.961.0510

chaid@kippchicago.org

github.com/chrishaid

*Work hard*. *Be nice.*
