### ISSUE TITLE
Enforce HTTPS protocol for package website?

### ISSUE THREAD

**Issue by IndrajeetPatil** [sfirke/janitor#469]
![image](https://user-images.githubusercontent.com/11330453/150477556-2f97af82-ae5f-4138-ad91-8a5eb46c8281.png)

**Comment by sfirke** [comment]
Do you (or anyone else) have a suggestion for what to do about this?

**Comment by IndrajeetPatil** [comment]
Have a look at this:
https://twitter.com/patilindrajeets/status/1465314949027225603?s=20
