### ISSUE TITLE
FR: support all classes by default in clean_names()

### ISSUE THREAD

**Issue by DanChaltiel** [sfirke/janitor#481]
Hi,

This is a very minor FR, so feel free to reject it without any regard.

By default, `clean_names()` only support a few arbitrary classes and justifies it like this:

> `clean_names()` is intended to be used on data.frames and data.frame-like objects. For this reason there are methods to support using `clean_names()` on `sf` and `tbl_graph` (from tidygraph) objects. For cleaning other named objects like named lists and vectors, use `make_clean_names()`.

However, it seems that the dataframe method works out of the box for lists and vectors as well:

``` r
library(dplyr)
clean_names = janitor:::clean_names.data.frame 

c("A%"=1, "some naME"=2) %>% clean_names()
#>  a_percent some_na_me 
#>          1          2
list("A%"=1, "some naME"=2) %>% clean_names()
#> $a_percent
#> [1] 1
#> 
#> $some_na_me
#> [1] 2
```
<sup>Created on 2022-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

To tell, my code often ends up with this unattractive `:::` attribution.

Could you consider adding this behavior in `janitor:::clean_names.default()` instead?

**Comment by billdenney** [comment]
I think that adding it to the default method if we can come up with a good test to make sure that the behavior was the intended behavior would be good.

My first thought is that as long as `length(names(x)) == length(x)`, then the data.frame method would work.  Can anyone think of an exception to that rule?

The data.frame method is really simple as just this one line, so it seems like it would work to me:

https://github.com/sfirke/janitor/blob/ab90c1af206576ce85f604af6cf1006e85555fc7/R/clean_names.R#L73-L75

The reason I wouldn't want to make the default method always point to the data.frame method is that would likely not have the expected result sometimes:

``` r
foo <- matrix(NA, nrow=2, ncol=2, dimnames=list(c("A B", "B C"), c("C D", "D E")))
names(foo)
#> NULL
janitor:::clean_names.data.frame(foo)
#>     C D D E
#> A B  NA  NA
#> B C  NA  NA
#> attr(,"names")
#> [1] NA NA NA NA
```

<sup>Created on 2022-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DanChaltiel** [comment]
`!is.null(names(x))` seems sufficient to me 👍 

However, as lists and vectors don't always have names, unlike data.frames, the output can be a little unexpected sometimes:

``` r
x = c("A%"=1, 2, 3)
names(x)
#> [1] "A%" ""   ""
janitor:::clean_names.data.frame(x)
#> a_percent         x       x_2 
#>         1         2         3
```
<sup>Created on 2022-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think that a warning if `any(names(dat)==""))` would do, don't you think? (maybe with a `verbose` option to silence it).


The matrix case looks like a corner case, and TBH I don't think many people care to clean matrix names. That being said, since matrices deal with names in their own way, they could have a specific method:
``` r
foo <- matrix(NA, nrow=2, ncol=2, dimnames=list(c("A B", "B C"), c("C D", "D E")))
clean_names.matrix = function(dat, ...) {
  colnames(dat) <- janitor::make_clean_names(colnames(dat))
  rownames(dat) <- janitor::make_clean_names(rownames(dat))
  dat
}
clean_names.matrix(foo)
#>     c_d d_e
#> a_b  NA  NA
#> b_c  NA  NA
```

<sup>Created on 2022-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sfirke** [comment]
This is all amenable to me, and it seems like a small but nice feature to be able to pipe `clean_names()` for a vector or list.  @DanChaltiel and @billdenney if you want to put something together, go for it.

> However, as lists and vectors don't always have names, unlike data.frames, the output can be a little unexpected sometimes:

I think that example is fine, IMO, with ideal behavior.  There I would hold the user responsible for paying attention to the names of their input and/or their output.  `clean_names()` is operating as safely as possible and not doing anything unexpected so I'm not sure it needs a warning.  Or if we thought a warning was needed, we'd probably want it for data.frames too.

**Comment by billdenney** [comment]
@DanChaltiel , Would you be able to put together a PR for this?

As it relates to @sfirke's comment, I agree that the user does have a responsibility to know something about their data and how to use it.  In your partially-named vector example (copied below), I think that what occurs is the correct behavior.  

```
x = c("A%"=1, 2, 3)
names(x)
#> [1] "A%" ""   ""
janitor:::clean_names.data.frame(x)
#> a_percent         x       x_2 
#>         1         2         3
```

The reason is that names which come out of `clean_names()` should be just that: clean.  I think that the behavior below is difficult to reconcile:  names(x) indicates that an empty string is the name for the second and third index, and names(z) indicates that an empty string is the second index.  But, I can't index on a name of `""`.  (FYI, I know the R language limitation on empty strings and NA as names, but there are times when you can get them in loading messy data.)

``` r
x <- c("A%"=1, 2, 3)
names(x)
#> [1] "A%" ""   ""
x[""]
#> <NA> 
#>   NA

y <- janitor:::clean_names.data.frame(x)
names(y)
#> [1] "a_percent" "x"         "x_2"
y["x"]
#> x 
#> 2

z <- setNames(data.frame(A=1, B=2), c("A", ""))
names(z)
#> [1] "A" ""
z[, ""]
#> Error in `[.data.frame`(z, , ""): undefined columns selected
```

<sup>Created on 2022-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

So, for the actual implementation of the new `clean_names.default()`:

* If `names(x)` is `NULL`:
    * Try `dimnames(x)` and go down a path that would work for arrays, matrices, and similar objects that respond to `dimnames()` but not `names()`.
* If `names(x)` is not `NULL`:
    * Use what is now the `clean_names.data.frame()` method.
* if `dimnames(x)` is not `NULL`:
    * Clean each of the outputs of `dimnames()` and put them back.
* If neither `names()` or `dimnames()` gives a non-NULL result, give an error.

Does that sound about right?

**Comment by DanChaltiel** [comment]
That sounds right, I'll make a PR as soon as I can free up some time.

**Comment by DanChaltiel** [comment]
A few comments while I'm working on the PR:
 - `clean_names.data.frame()` is now handled in `clean_names.default()` and will be removed
 - if both names and dimnames are null, shouldn't we better return the unchanged object with a warning? If one has an automated workflow, throwing an error could break things unnecessarily.

**Comment by billdenney** [comment]
@DanChaltiel , thanks for working on this!

Yes, it makes sense that the data.frame method would go away.

Based on @sfirke's comment above (and my belief, too), the user should know something about their data.  If the user sends something into `clean_names()` that has no names, then there has usually been a programming issue previously in the code.  Even in automated workflows, if an unnamed object is coming through, then the user should know about it. So, please do make it an error if there are no names to clean.
