### ISSUE TITLE
Feature request: `is_dupes()`

### ISSUE THREAD

**Issue by brunomioto** [sfirke/janitor#485]
## Feature requests

The `get_dupes()` function returns a data.frame with the duplicated names.
The new `is_dupes()` would return a TRUE/FALSE when there's another name/value duplicated on the dataset.

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<pre class="r"><code>data.frame(
  x = c(&quot;Brazil&quot;, &quot;US&quot;, &quot;Brazil&quot;, &quot;China&quot;, &quot;UK&quot;),
  is_dupes = c(TRUE, FALSE, TRUE, FALSE, FALSE)
)
#&gt;        x is_dupes
#&gt; 1 Brazil     TRUE
#&gt; 2     US    FALSE
#&gt; 3 Brazil     TRUE
#&gt; 4  China    FALSE
#&gt; 5     UK    FALSE</code></pre>
<p><sup>Created on 2022-06-29 by the <a href="https://reprex.tidyverse.org">reprex package</a> (v2.0.1)</sup></p>

**Comment by sfirke** [comment]
I think these two lines do it:
```
mtcars %>%
  dplyr::add_count(mpg, name = "is_dupe") %>%
  dplyr::mutate(as.logical(is_dupe-1))
```

A janitor function would likely just be wrapping that.  Given that it's just two lines in dplyr, and the limited capacity for developing janitor, I'm going to close this as unplanned.  And I apologize for taking so long to acknowledge this suggestion! 😔
