### ISSUE TITLE
Add Descriptive Name To First Column Of Tably And Sort N Descending

### ISSUE THREAD

**Issue by gfleetwood** [sfirke/janitor#488]
This is a feature request for the tabyl function. Having a dot for a column name is awkward, especially if it becomes part of another workflow. I usually rename it to unique_values. 

Sorting n descending is just something else that came to mind that I often end up doing as well.

**Comment by sfirke** [comment]
What command are you using that gives you a dot for a column name?

The sorting has been discussed before and was actually in an early version of `tabyl` but was removed.  I suggest piping to `%>% arrange(desc(n))` after loading `dplyr`.

**Comment by gfleetwood** [comment]
That's why I've been doing for the sorting. As for the column name, I'm on Ubuntu 20.04 using R 4.2.1 and janitor 2.1.0:

``` r
library(tidyverse)

iris %>% 
  pull(Species) %>% 
  janitor::tabyl()
#>           .  n   percent
#>      setosa 50 0.3333333
#>  versicolor 50 0.3333333
#>   virginica 50 0.3333333
```

<sup>Created on 2022-09-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sfirke** [comment]
Ah, the `pull` gives you an unnamed vector, no way to know what that input should be named.  Try instead simply:
```
iris %>% tabyl(Species)
    Species  n   percent
     setosa 50 0.3333333
 versicolor 50 0.3333333
  virginica 50 0.3333333
```

**Comment by sfirke** [comment]
Or `tabyl(iris$Species)`

**Comment by gfleetwood** [comment]
Got it. Thanks.
