### ISSUE TITLE
factors to character

### ISSUE THREAD

**Issue by almartin82** [sfirke/janitor#49]
Sam, one thing that I've run into recently is output of other packages (especially the stuff that reads in Access files... ugh) that doesn't give fine control to the read.csv parameters - I've been having to take the data frame as it comes, and then flip factors back to character.

Is that something that should live in janitor?  If I made a pull request, would you be likely to accept?

**Comment by sfirke** [comment]
Would this be a function that converts all factor columns to characters?  There's a purrr one-liner that seems to do that:
`df %>% map_if(is.factor, as.character) -> df`
(from [here](http://stackoverflow.com/questions/2851015/convert-data-frame-columns-from-factors-to-characters))

Would the function be more than that?

**Comment by almartin82** [comment]
Yeah, that's basically what I've been doing. It's been more challenging
than that one liner because I have been working with the mdb-get function
from Hmisc, which puts these S3 labels on every data frame... `dmap_if`
doesn't like it at all. See
https://github.com/almartin82/nyschooldata/blob/master/R/assess_db.R#L57
for more. Maybe this is just an edge case though.

**Comment by sfirke** [comment]
Is the Hmisc `labelled` class the same one produced by `haven::read_sav()`?  I and a colleague both often want to go labelled -> factor.  I used to have a janitor function for that, but I removed it.  it felt too niche and I thought it might make haven a requirement of the package, though I'm new to understanding that part of package development.  If a similar function would solve both of our problems, and it's a widespread issue with a non-trivial solution, I think a solution could be within scope.

**Comment by sfirke** [comment]
I haven't worked with it a ton yet but the `sjlabelled` package looks pretty robust for dealing with factor conversions.  At this point I'd be surprised if this kind of functionality doesn't already exist elsewhere.  Closing this as I clean up issues a bit.
