### ISSUE TITLE
bug in adorn_percentages(denominator = "col")

### ISSUE THREAD

**Issue by mgacc0** [sfirke/janitor#490]
``` r
      library(janitor)      
      mtcars %>%
        tabyl(am, cyl) %>%
        adorn_totals(c("row", "col")) %>%
        adorn_percentages(denominator = "col")
#> Error in FUN(X[[i]], ...): only defined on a data frame with all numeric-alike variables
```

**Comment by jzadra** [comment]
This code works fine for me.  Double check that you don't have any other packages loaded that have conflicting function names?


``` r
 library(janitor)      
#> 
#> Attaching package: 'janitor'
#> The following objects are masked from 'package:stats':
#> 
#>     chisq.test, fisher.test
      mtcars %>%
        tabyl(am, cyl) %>%
        adorn_totals(c("row", "col")) %>%
        adorn_percentages(denominator = "col")
#>     am         4         6         8   Total
#>      0 0.2727273 0.5714286 0.8571429 0.59375
#>      1 0.7272727 0.4285714 0.1428571 0.40625
#>  Total 1.0000000 1.0000000 1.0000000 1.00000
```

**Comment by mgacc0** [comment]
I have the current development version of dplyr
dplyr          1.0.99.9000 2022-10-05 [1] Github (tidyverse/dplyr@1a7061f)

Could it be related?
Will this be a bug in the near future (when the dplyr development version arrives to CRAN)?

**Comment by jzadra** [comment]
@sfirke I am able to reproduce this error with dplyr 1.0.99.9000

**Comment by sfirke** [comment]
Yikes, thanks for reporting and figuring out the underlying issue! I'll
start looking into a fix.

**Comment by sfirke** [comment]
Past Sam (blame him) had relied on `dplyr::last()` returning the last column when called on a data.frame: https://github.com/sfirke/janitor/blob/main/R/adorn_percentages.R#L94-L96

  That behavior has changed according to dplyr's NEWS.md:
> first(), last(), and nth() have been rewritten to use vctrs. This comes with the following improvements (#6331):
>
>    When used on a data frame, these functions now return a single row rather than a single column. This is more consistent with the vctrs principle that a data frame is generally treated as a vector of rows.

Seems reasonable.  When I got to this line of the current code, I was kind of surprised it even works as-is.  I'll refactor to base R, which it should have been in the first place.

**Comment by sfirke** [comment]
@mgacc0 feel free to install the latest commit here with `remotes::install_github("sfirke/janitor")` and see if your code works again

**Comment by mgacc0** [comment]
> @mgacc0 feel free to install the latest commit here with `remotes::install_github("sfirke/janitor")` and see if your code works again

Now it works as good as before. 👏
