### ISSUE TITLE
Official notice of impending dplyr 1.1.0 release

### ISSUE THREAD

**Issue by DavisVaughan** [sfirke/janitor#506]
@sfirke I noticed that you have already fixed https://github.com/sfirke/janitor/pull/491, which is great!

It came up in our revdep check as breaking {questionr}, but surprisingly didn't break janitor.

We are planning on releasing dplyr 1.1.0 on January 27th, so hopefully you have plenty of time to get a janitor release in before that. Thanks!

**Comment by sfirke** [comment]
Thanks for this notice!  Yep, we're planning a submission to CRAN ahead of that Jan 27th dplyr submission.  V2.2 is being tracked here for anyone interested: https://github.com/sfirke/janitor/milestone/4
