### ISSUE TITLE
Submit janitor v2.2 to CRAN

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#509]
- [x] Go through issues
- [x] Resolve issues tagged with milestone 2.2
- [x] Run `revdep_check`, notify :package: maintainers if needed
- [x] Run `revdep_check` again after fixing #513 
- [x] Update CRAN comments
- [x] Bump version number
- [x] Submit, announce, etc. - follow the steps here https://r-pkgs.org/lifecycle.html#sec-release

**Comment by sfirke** [comment]
Eep I see dplyr 1.1.0 is released yesterday on CRAN: https://cran.r-project.org/web/packages/dplyr/index.html  So right now #490 will affect users with the latest version of all packages.

I think I'm done with almost everything except some documentation.  And I need to run revdep_check but don't expect that will raise any issues.  I should be able to submit to CRAN this week!

**Comment by MichaelChirico** [comment]
Thanks for the update!

**Comment by sfirke** [comment]
`revdepcheck::revdep_check()` passed.  Here's `cran.md`:

```
## revdepcheck results

We checked 101 reverse dependencies (98 from CRAN + 3 from Bioconductor), comparing R CMD check results across CRAN and dev versions of this package.

 * We saw 0 new problems
 * We failed to check 0 packages
```

**Comment by billdenney** [comment]
Hooray!!!

**Comment by jzadra** [comment]
Nice work, you've been at it hard the last several weeks!

**Comment by sfirke** [comment]
Submitted!  I'll wait to hear from CRAN and then tag the release on Github.

**Comment by sfirke** [comment]
Gotta fix more URL formats.  Kinda funny, apparently I had this same problem when I last submitted 2 years ago:
![image](https://user-images.githubusercontent.com/7569808/216373947-14b50dd7-fe1b-4d54-a7ce-386fc8083908.png)

**Comment by sfirke** [comment]
janitor 2.2.0 is [live on CRAN](https://cran.r-project.org/web/packages/janitor/index.html)! 🎉

**Comment by billdenney** [comment]
Hooray!

**Comment by sfirke** [comment]
Whew.  A few postmortem thoughts:
 - 👍 It was good that we merged the `clean_names` stuff a month before the release so there was time to try it out, discuss, and unwind it thoughtfully
 - 👎 I worked on the busiest final moments of this release on two different machines and it got me mixed up
