### ISSUE TITLE
canonical dirty data data.frame

### ISSUE THREAD

**Issue by almartin82** [sfirke/janitor#51]
this really should exist - [this](https://cran.r-project.org/doc/contrib/de_Jonge+van_der_Loo-Introduction_to_data_cleaning_with_R.pdf) paper links to `dirty_iris`, available on [github](https://raw.githubusercontent.com/edwindj/datacleaning/master/data/dirty_iris.csv)

That is somewhat dirty, but it doesn't have a lot of the 'in the wild' features that I see all the time (off the top of my head: data that is supposed to be numeric but has a NA / missing code that R interprets as character).

The tests that you have here are great but it'd be great to have examples against a nasty data file that looks similar to something that might be seen in the wild.

You can assign me this issue if you'd like :smile:

**Comment by sfirke** [comment]
I like this!  I originally had a short little .csv to go with this package, to illustrate dirty features and cleaning them.  It wasn't truly nasty though.

I agree that the `dirty_iris.csv` file is not real-world dirty.  That set has this as dirtiness:

> – The petal length of an iris is at least 2 times its petal width.
> – The sepal length of an iris cannot exceed 30 cm.
> – The sepals of an iris are longer than its petals

That might be called semantic dirtiness?  Or something.  I'm more interested in, say, lines of whitespace used horizontally and vertically as delimiters in an Excel file, for instance.  Or the bad NA value in a numeric column that you mention.  Dates are often screwy like this.

I will assign this to you, thanks for offering!

**Comment by sfirke** [comment]
It won't let me assign this to you.  Not sure why, after some Googling.

**Comment by almartin82** [comment]
I think you're right - just assigned myself (a KIPP-ism 😄 )

**Comment by almartin82** [comment]
Been thinking about this - it would be nice for each row to identify how/why it was dirty, to help surface test success/failure.

**Comment by sfirke** [comment]
I was thinking more about this yesterday.  It would make for a cool vignette to have a **dirty** Excel file that gets cleaned one step at a time.  We could make a .csv too but then is that really as dirty? :smiling_imp:

**Comment by sfirke** [comment]
whoops I accidentally closed this

**Comment by sfirke** [comment]
I am working on this right now and it is cathartic to create some ugly data - I think you will like it.  If it's not in a spreadsheet made by a novice, it's not _really_ dirty data.

**Comment by almartin82** [comment]
there's [this](https://figshare.com/articles/Wellcome_Trust_APC_spend_2012_13_data_file/963054) gnarly spreadsheet of spending on journals.

@jennybc's [jailbreakr](https://github.com/rsheets/jailbreakr) project points to the Enron corpus - maybe grab a subset of those?

**Comment by jennybc** [comment]
The spreadsheets that underpin the gapminderpackage have some lovely features 😂 and, since I use it to teach data cleaning, the whole glorious mess is laid out here:

https://github.com/jennybc/gapminder/tree/master/data-raw#readme

**Comment by sfirke** [comment]
Filing this under, I would love to see this happen, but realistically I am not going to get to it - so closing as I tidy up issues.
