### ISSUE TITLE
Bug: adorn_totals() on one-way tabyl changes attribute to two_way

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#523]
This causes `adorn_pct_formatting()` to incorrectly adorn the Ns column.  Found this as I skimmed a vignette, trying to fix URL formatting to meet CRAN standards.  😩

**Comment by billdenney** [comment]
To install an older version, some instructions are here: https://support.posit.co/hc/en-us/articles/219949047-Installing-older-versions-of-packages

**Comment by sfirke** [comment]
oh HO!  How tricky, I *deleted* the lines back in Dec 2021 I was about to propose adding as a fix.  In this PR.  https://github.com/sfirke/janitor/pull/464/files

**Comment by sfirke** [comment]
Basically the call to `as_tabyl` in `adorn_totals` was tagging the `two_way` attribute onto `one_way` tabyls so then subsequent functions like `adorn_pct_formatting()` incorrectly were applied to that second column (N).

E.g. in this case:
```
mtcars %>%
  tabyl(am) %>%
  adorn_totals("row") %>%
  adorn_pct_formatting()
```

The resulting column `n` had `adorn_pct_formatting()` applied to it and looked like `1900.00%` instead of `19`.

**Comment by sfirke** [comment]
And this bug was introduced Dec 2021 so hasn't ever gone to CRAN.  Whew, I escaped introducing it!
