### ISSUE TITLE
adorn_totals() attempting to add additional "Total" factor level

### ISSUE THREAD

**Issue by egozoglu** [sfirke/janitor#529]
## Bug reports
adorn_totals() attempting to add additional "Total" factor level, leading to error.
---

adorn_totals() is attempting to add factor layer "Total" if a table was subject to adorn_totals() previously. This leads to error as "Total" layer already exist for the factor.

```r
library(janitor)
#> 
#> Attaching package: 'janitor'
#> The following objects are masked from 'package:stats':
#> 
#>     chisq.test, fisher.test
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

test <-iris |>
  mutate(Species = factor(Species, levels = c("setosa", "versicolor", "virginica")))

summary_1 <- test |>
  group_by(Species) |>
  select(Species, everything()) |>
  adorn_totals()

summary_2 <- summary_1 |>
  filter(Species != "Total")

summary_3 <- summary_2 |>
  group_by(Species) |>
  select(Species, everything()) |>
  adorn_totals()
#> Error in `levels<-`(`*tmp*`, value = as.character(levels)): factor level [5] is duplicated
```

**Comment by sfirke** [comment]
Makes sense, I can see how the change I introduced just before 2.2.0 in #494 would have caused this.  And I think it's an easy fix.

I can patch it but I'm curious about a workflow that calls `adorn_totals()` twice.

**Comment by egozoglu** [comment]
I think a check of whether "name" already exists in levels prior to re-leveling at adorn_totals.R Line 137 could potentially solve the issue.

Re: workflow example calling adorn_totals() twice - real life case is actually coming from joining two tables where one of them was previously subject to adorn_totals(). When adorn_totals() is applied to this new joined table, error was thrown.

**Comment by sfirke** [comment]
I think this will do it: https://github.com/sfirke/janitor/pull/531  Indeed, I'm targeting the line you suggest.  Thanks for looking through the codebase!

**Comment by sfirke** [comment]
@egozoglu when you get a chance can you install the latest janitor from Github and confirm that this addresses your issue?

**Comment by egozoglu** [comment]
Thanks for the quick fix! I think this solves the issue.

While testing different use cases - I saw that when adorn_totals() is called twice on the table, it also results in I think in an handled error (Line 67). While I understand this, I think there are cases where someone might want to "refresh" the totals. There might be a better way to do this, however, instead of an "error", would that be possible to convert this to a verbose "reminder" and still proceed with updating the "total" row?

Example below:

```
library(janitor)
#> 
#> Attaching package: 'janitor'
#> The following objects are masked from 'package:stats':
#> 
#>     chisq.test, fisher.test
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
test <-iris |>
  mutate(Species = factor(Species, levels = c("setosa", "versicolor", "virginica")))

summary_1 <- test |>
  group_by(Species) |>
  select(Species, everything()) |>
  adorn_totals()

summary_2 <- summary_1 |>
  filter(Species != "Total")

summary_3 <- summary_2 |>
  group_by(Species) |>
  select(Species, everything()) |>
  adorn_totals()

summary_4 <- summary_3 |>
  bind_rows(summary_1) |>
  adorn_totals()
#> Error in adorn_totals(bind_rows(summary_3, summary_1)): trying to re-add a totals dimension that is already been added
```
