### ISSUE TITLE
Require character input to `make_clean_names()`

### ISSUE THREAD

**Issue by billdenney** [sfirke/janitor#532]
## Feature requests

I often accidentally pass in a data.frame to `make_clean_names()` when I mean to use `clean_names()`.  It then takes me forever (about 30 seconds) to figure out what I'm doing wrong.

I think it would be better to give an error if a data.frame is passed in to `make_clean_names()`.  I'd say that we should allow anything else rather than requiring a character string because maybe a factor could be cleaned, for example.

**Comment by sfirke** [comment]
Sure, this seems like a nice addition. Just check if the input is a
data.frame and if so error with a message saying, did you mean to call
clean_names?

We could go down the path of checking that the input is atomic but idk if
it's necessary - the above fix would in practice provide the vast majority
of the benefit and have no chance of unintended side effects.

Want to send a simple PR for this?
