### ISSUE TITLE
make_clean_names: Case conversions are wierd

### ISSUE THREAD

**Issue by KasperThystrup** [sfirke/janitor#571]
## Feature request or Bug

I'm not sure whether this is the intention, however when calling make_clean_names on an string containing uppercase characters followed by a lowercase string, it will insert an underscore split just before the last character of the uppercase string.

A few examples:
* ASDFnr becomes asd_fnr
* ASDfnr becomes as_dfnr
* ASDFNR and asdfnr both becomes asdfnr

It would be more usefull if the underscore was placed just before the lowercased characters, instead of one character before that.
ASDFnr should become asdf_nr
ASDfnr should become ASD_fnr
etc.

```r
> janitor::make_clean_names("asdfnr")
[1] "asdfnr"
> janitor::make_clean_names("ASDFnr")
[1] "asd_fnr"
> janitor::make_clean_names("ASDFNR")
[1] "asdfnr"
> janitor::make_clean_names("ASDfnr")
[1] "as_dfnr"
```

**Comment by billdenney** [comment]
While I understand that the behavior is not perfect in all cases, it is the intended behavior.  The concept of the feature is that it will help separate words starting with capital letters.  You can change the behavior using the `parsing_option` argument to `make_clean_names()`:

``` r
library(janitor)
#> 
#> Attaching package: 'janitor'
#> The following objects are masked from 'package:stats':
#> 
#>     chisq.test, fisher.test
make_clean_names("ASDfnr", parsing_option = 2)
#> [1] "asd_fnr"
```

<sup>Created on 2024-05-08 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
