### ISSUE TITLE
Add codecov token to resolve failure 

### ISSUE THREAD

**Issue by olivroy** [sfirke/janitor#576]
See https://github.com/r-lib/actions/issues/834 for info

This requires admin right to fix.

**Comment by billdenney** [comment]
@sfirke, that will require your management.

**Comment by sfirke** [comment]
I just added a value for `CODECOV_TOKEN` as a repo secret.  I don't see the failure, I'm probably not looking in the right place - did that resolve it?

**Comment by olivroy** [comment]
@sfirke I am referring to https://github.com/sfirke/janitor/actions/runs/9194907436/job/25289461527! So next time a commit is merged to main, it should pass with your change!

Thanks
