### ISSUE TITLE
Multi-Header Support

### ISSUE THREAD

**Issue by patternproject** [sfirke/janitor#68]
Please add support for headers that are either:

1) Having Text arranged in Vertical or direction other than horizontal. Such as those in the attached file. 
![trouble headers](https://cloud.githubusercontent.com/assets/5774371/19151184/be7389e6-8be4-11e6-888d-915033ba1b70.PNG)

2) Text in table with cross / or \ split. Such as those in the attached file. 

Please tweet at @patternproject for any additional feedback.

**Comment by sfirke** [comment]
Sorry I'm coming to this suuuuper late 🐌 

1) I just tried reading vertical column labels with `readxl::read_excel` and it seemed to succeed, in the above example it would get "Database" etc.

2) The diagonal split ... _shudder_.  Looks like that's a trick of formatting, but still a single value?  According to http://www.exceltip.com/tips/split-a-cell-diagonally-in-microsoft-excel.html at least - I haven't worked with these split cells before.

In that case I expect it reads in the above as something like `"Skill set       Projects"` (with more whitespace between them)?  I don't see how to support processing that kind of header.  At least it should only happen once, and you can get by with splitting the first name on the whitespace and taking just the latter entry (as "Skill set" seems to describe the subsequent columns and is not needed, retain "Projects").

I'll close for now as I'm tidying up.  If you or others have ideas for a function that could be useful here, and a working example of an Excel file to tinker with, we can reopen this.
