### ISSUE TITLE
verbose options to remove_empty_ functions

### ISSUE THREAD

**Issue by jbkunst** [sfirke/janitor#70]
Hi @sfirke ,

Thanks for this package. Works really well in first step of every analysis.

A lot of times you don't kown a priori your load data set but anyway you want to clean it with the `remove_empty_` functions ,and sometimes we want to know what/how much we removed. 

```
options(janitor.verbose = TRUE)

data <- data_raw %>%
  remove_empty_rows() %>%
  remove_empty_cols()

# as messages
3.234 (45%) rows removed
4 (5%) columns removed (colna1, colna2, ...)
```

Do you think this useful to add to your janitor package?

**Comment by sfirke** [comment]
Sure, I could see a `quiet = TRUE` argument or similar to these functions; if specified as FALSE, it would print the outputs as you have above.  BTW I'm thinking about combining them into a single `remove_empty()` function.

**Comment by billdenney** [comment]
I wanted this today, and generated a PR based on the comments above.  Let me know if you think it covers the need.
