### ISSUE TITLE
Create update_cols function

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#73]
Supply a main data.frame and one with a join-by ID as well as columns sharing names of the main DF.  This swaps in values in the auxiliary data.frame, but leaves the original values in place if there's no new one to overwrite with.

Not sure how widespread this is, have to weigh popularity against bloating the package.  But I had to do a lot of this recently and have a sketch of the code already:

```
function(x) {
  left_join(x, aux_df, by = c("TT2 ID")) %>%
    mutate(`ACE Status` = use_first_valid_of(`ACE Status.y`, `ACE Status.x`),
           `Certification Status` = use_first_valid_of(`Certification Status.y`, `Certification Status.x`),
           `Date Certified/Extended/Removed` = use_first_valid_of(`Date Certified/Extended/Removed.y`, `Date Certified/Extended/Removed.x`),
           `ETS Status` = use_first_valid_of(`ETS Status.y`, `ETS Status.x`)) %>%
    select(-contains(".")) %>% # drop the .x and .y overlapping variables
    select(one_of(original_col_order))
}
```

**Comment by rgknight** [comment]
This is an upsert, more or less. I'd like to see it in "base" `dplyr`. Maybe chime in on the `dplyr` issue. https://github.com/hadley/dplyr/issues/2075

**Comment by sfirke** [comment]
Yep @rgknight is correct, if tidyr adds an upsert like discussed here it'll likely be better than whatever we'd do.  Closing this, keep an eye on https://github.com/tidyverse/tidyr/issues/183.
