### ISSUE TITLE
How is use_first_valid_of different from dplyr's coalesce?

### ISSUE THREAD

**Issue by rgknight** [sfirke/janitor#74]
Would be helpful to have an explanation in the help file, if it is indeed different.

https://github.com/hadley/dplyr/blob/master/R/coalesce.R

**Comment by sfirke** [comment]
Great catch.  It's not that different :-(  I didn't know about `dplyr::coalesce`.

I compared them and think they are close enough that `use_first_valid_of` should be deprecated and phased out, with a message to use `dplyr::coalesce` instead.  There are two features in `use_first_valid_of` that are missing in `coalesce`:

1. If there are any type mismatches in the input vectors, the output is coerced to a character vector (with a message).  In `coalesce`, the operation fails with a warning.  Stylistic difference, and okay with me.
2. Factors are coerced to `character` in `use_first_valid_of`, while `coalesce` fails:
```
> x <- factor(c("a", NA))
> y <- factor(c("b", "c"))
> use_first_valid_of(x, y)
[1] "a" "c"
Warning message:
In use_first_valid_of(x, y) :
  Input vectors are of class 'factor' and will be coerced to class 'character' before combining
> coalesce(x, y)
[1] a    <NA>
Levels: a
Warning message:
In `[<-.factor`(`*tmp*`, i, value = 2L) :
  invalid factor level, NA generated
```

Course of action:

- [ ] Deprecate `use_first_valid_of` with message referring to `coalesce`
- [ ] Post dplyr issue identifying issue 2 above; acceptable if `coalesce` can't handle factors but in that case it should fail with an error message, not return the current output, IMO.

**Comment by rgknight** [comment]
I haven't looked too closely at  `convert_to_NA`, but it may also be a candidate for deprecation with a pointer to dplyr's `na_if`?

**Comment by rgknight** [comment]
I submitted an issue on dplyr for this https://github.com/hadley/dplyr/issues/2254

**Comment by sfirke** [comment]
Updating the vignette to remove the deprecated `convert_to_NA` and I kind of want to put it back after reading this discussion: https://github.com/tidyverse/dplyr/issues/1972...
