### ISSUE TITLE
Running totals 

### ISSUE THREAD

**Issue by dsdesrosiers** [sfirke/janitor#78]
Apologies if this is a redundant request I searched but didn't see any immediate match ... a running total option for the tabyl function would be awesome.

Thanks for the consideration - 
Danielle D

**Comment by randomgambit** [comment]
you dont need `janitor` to do that. Basically the output you get is a dataframe already. Just use `dplyr` : `mutate(cumsum = cumsum(mycol))`

**Comment by randomgambit** [comment]
but I agree that might be an interesting option - getting the cumulative sum of the percentage counts.

**Comment by sfirke** [comment]
I entirely get the convenience of this - I like it in SPSS tabulations.  But now that I've redone tabyl to cover combinations of 1, 2, or 3 variables, I don't think I can fit it in cleanly.  Part of the reason I got rid of the `sort` argument in the next version of janitor is that the user can just do ` %>% dplyr::arrange(desc(n))`, and here I think what @randomgambit suggests is similarly efficient.
