### ISSUE TITLE
feature request : summary stats like a boss

### ISSUE THREAD

**Issue by randomgambit** [sfirke/janitor#84]
Hello Sam,

How are you? I am still using `janitor` for my research papers. It's great and we already discussed that in another issue.

I was wondering if, going forward, you would include some other summary stats functions in the vein of `tabyl` and `crosstab`. That is something that quickly summarises all of (of some subset) of the columns of a dataframe, by distinguishing between factors and numerical vectors, counting unique and missing values and others. 

At the moment this simple summary stat function is not availble yet in the `tidyverse`. `Glimpse` is kind of OK, but nowhere near as complete as a proper summary stats outputs. 

What do you think? Then `janitor` would be a complete tool for quickly and (aestetically) exploring a dataframe ;-)

**Comment by rgknight** [comment]
I'd be interested in learning more about what you think it would take to do this well. Do you have an example of a command from another language that you think does this well?

`epiDisplay` has some tools that I have used in the past (distant past when it was called `epicalc`...)  You may want to check that out.

**Comment by sfirke** [comment]
I saw some #[rstats twitter chatter about this](https://twitter.com/rdpeng/status/775114831078821888) and it looks like Hadley intends to have a summary function like this in vctrs: https://github.com/hadley/vctrs/issues/17

I'm inclined to wait for now and see what that turns into.

**Comment by rgknight** [comment]
I feel like you could say that about many of our functions :) For example, I found plans for a `set_key` function in dplyr the other day that would do a lot of the duplicate and missing checks that we discussed. In any case, I agree that this isn't a priority.

One of the things that I used to do when I was working more with survey data is create an Rmd document that prints a bar chart for every factor, some summary stats and a small histogram for every number and the text of open response fields. Kind of like the summary of responses in Google forms. 

I could see a command that would generate and render the Rmd file being helpful. But not a priority.

**Comment by randomgambit** [comment]
hi guys im on vacation at the moment but i ll be back tomorrow with a detailed answer to your comments. thanks!

**Comment by randomgambit** [comment]
hi guys, have a quick read here if you want https://github.com/hadley/vctrs/issues/17
thanks!

**Comment by rgknight** [comment]
Take a look at https://github.com/hadley/precis

**Comment by sfirke** [comment]
This is worthwhile topic but it's big and may be tackled more robustly in those two packages linked above.  There's enough else to be done on janitor and elsewhere and this won't be something I get to.
